# TCL File Generated by Component Editor 18.1
# Mon Nov 22 16:20:07 MSK 2021
# DO NOT MODIFY


# 
# Switch "Switch" v1.0
#  2021.11.22.16:20:07
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module Switch
# 
set_module_property DESCRIPTION ""
set_module_property NAME Switch
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME Switch
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ELABORATION_CALLBACK elaborate
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL Switch
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file Switch.sv SYSTEM_VERILOG PATH ./Switch.sv TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter INPUT_NUMBER INTEGER 5
set_parameter_property INPUT_NUMBER DEFAULT_VALUE 5
set_parameter_property INPUT_NUMBER DISPLAY_NAME INPUT_NUMBER
set_parameter_property INPUT_NUMBER TYPE INTEGER
set_parameter_property INPUT_NUMBER UNITS None
set_parameter_property INPUT_NUMBER ALLOWED_RANGES {1 2 3 4 5 6 7 8}
set_parameter_property INPUT_NUMBER HDL_PARAMETER true
add_parameter PIX_IN_PARALLEL INTEGER 4
set_parameter_property PIX_IN_PARALLEL DEFAULT_VALUE 4
set_parameter_property PIX_IN_PARALLEL DISPLAY_NAME PIX_IN_PARALLEL
set_parameter_property PIX_IN_PARALLEL TYPE INTEGER
set_parameter_property PIX_IN_PARALLEL UNITS None
set_parameter_property PIX_IN_PARALLEL ALLOWED_RANGES {1 2 3 4}
set_parameter_property PIX_IN_PARALLEL HDL_PARAMETER true
add_parameter OUTPUT_NUMBER INTEGER 2
set_parameter_property OUTPUT_NUMBER DEFAULT_VALUE 2
set_parameter_property OUTPUT_NUMBER DISPLAY_NAME OUTPUT_NUMBER
set_parameter_property OUTPUT_NUMBER TYPE INTEGER
set_parameter_property OUTPUT_NUMBER UNITS None
set_parameter_property OUTPUT_NUMBER ALLOWED_RANGES {1 2 3 4 5 6 7 8}
set_parameter_property OUTPUT_NUMBER HDL_PARAMETER true


# 
# display items
# 

# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clock clk Input 1

# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset_n Input 1


# 
# connection point control
# 
add_interface control avalon end
set_interface_property control addressUnits WORDS
set_interface_property control associatedClock clock
set_interface_property control associatedReset reset
set_interface_property control bitsPerSymbol 8
set_interface_property control burstOnBurstBoundariesOnly false
set_interface_property control burstcountUnits WORDS
set_interface_property control explicitAddressSpan 0
set_interface_property control holdTime 0
set_interface_property control linewrapBursts false
set_interface_property control maximumPendingReadTransactions 0
set_interface_property control maximumPendingWriteTransactions 0
set_interface_property control readLatency 0
set_interface_property control readWaitTime 1
set_interface_property control setupTime 0
set_interface_property control timingUnits Cycles
set_interface_property control writeWaitTime 0
set_interface_property control ENABLED true
set_interface_property control EXPORT_OF ""
set_interface_property control PORT_NAME_MAP ""
set_interface_property control CMSIS_SVD_VARIABLES ""
set_interface_property control SVD_ADDRESS_GROUP ""

add_interface_port control control_read read Input 1
add_interface_port control control_write write Input 1
add_interface_port control control_address address Input 5
add_interface_port control control_writedata writedata Input 32
add_interface_port control control_readdata readdata Output 32
set_interface_assignment control embeddedsw.configuration.isFlash 0
set_interface_assignment control embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment control embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment control embeddedsw.configuration.isPrintableDevice 0



proc elaborate {} {

	set ins [ get_parameter_value INPUT_NUMBER ]

	for { set inp 0 } { $inp < $ins } { incr inp } {
		add_interface din_${inp} avalon_streaming end
		set_interface_property din_${inp} associatedClock clock
		set_interface_property din_${inp} associatedReset reset
		set_interface_property din_${inp} dataBitsPerSymbol 8
		set_interface_property din_${inp} errorDescriptor ""
		set_interface_property din_${inp} firstSymbolInHighOrderBits true
		set_interface_property din_${inp} maxChannel 0
		set_interface_property din_${inp} readyLatency 0
		set_interface_property din_${inp} ENABLED true
		set_interface_property din_${inp} EXPORT_OF ""
		set_interface_property din_${inp} PORT_NAME_MAP ""
		set_interface_property din_${inp} CMSIS_SVD_VARIABLES ""
		set_interface_property din_${inp} SVD_ADDRESS_GROUP ""

		add_interface_port din_${inp} din_${inp}_data data Input 24*PIX_IN_PARALLEL
		add_interface_port din_${inp} din_${inp}_empty empty Input PIX_IN_PARALLEL
		add_interface_port din_${inp} din_${inp}_endofpacket endofpacket Input 1
		add_interface_port din_${inp} din_${inp}_ready ready Output 1
		add_interface_port din_${inp} din_${inp}_startofpacket startofpacket Input 1
		add_interface_port din_${inp} din_${inp}_valid valid Input 1
	}

	set outs [ get_parameter_value OUTPUT_NUMBER ]

	for { set inp 0 } { $inp < $outs } { incr inp } {
		add_interface dout_${inp} avalon_streaming start	
		set_interface_property dout_${inp} associatedClock clock
		set_interface_property dout_${inp} associatedReset reset
		set_interface_property dout_${inp} dataBitsPerSymbol 8
		set_interface_property dout_${inp} errorDescriptor ""
		set_interface_property dout_${inp} firstSymbolInHighOrderBits true
		set_interface_property dout_${inp} maxChannel 0
		set_interface_property dout_${inp} readyLatency 0
		set_interface_property dout_${inp} ENABLED true
		set_interface_property dout_${inp} EXPORT_OF ""
		set_interface_property dout_${inp} PORT_NAME_MAP ""
		set_interface_property dout_${inp} CMSIS_SVD_VARIABLES ""
		set_interface_property dout_${inp} SVD_ADDRESS_GROUP ""

		add_interface_port dout_${inp} dout_${inp}_endofpacket endofpacket Output 1
		add_interface_port dout_${inp} dout_${inp}_data data Output 24*PIX_IN_PARALLEL
		add_interface_port dout_${inp} dout_${inp}_empty empty Output PIX_IN_PARALLEL
		add_interface_port dout_${inp} dout_${inp}_ready ready Input 1
		add_interface_port dout_${inp} dout_${inp}_startofpacket startofpacket Output 1
		add_interface_port dout_${inp} dout_${inp}_valid valid Output 1
	}

}



