# TCL File Generated by Component Editor 18.1
# Fri May 22 21:42:50 MSK 2020
# DO NOT MODIFY


# 
# bond_ifc "bond_ifc" v1.0
#  2020.05.22.21:42:50
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module bond_ifc
# 
set_module_property DESCRIPTION ""
set_module_property NAME bond_ifc
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME bond_ifc
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL bond_ifc
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file bond_ifc.sv SYSTEM_VERILOG PATH bond_ifc.sv TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock csi_clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset rsi_reset reset Input 1


# 
# connection point slave
# 
add_interface slave avalon end
set_interface_property slave addressUnits WORDS
set_interface_property slave associatedClock clock
set_interface_property slave associatedReset reset
set_interface_property slave bitsPerSymbol 8
set_interface_property slave burstOnBurstBoundariesOnly true
set_interface_property slave burstcountUnits WORDS
set_interface_property slave explicitAddressSpan 0
set_interface_property slave holdTime 0
set_interface_property slave linewrapBursts false
set_interface_property slave maximumPendingReadTransactions 48
set_interface_property slave maximumPendingWriteTransactions 0
set_interface_property slave readLatency 0
set_interface_property slave readWaitTime 1
set_interface_property slave setupTime 0
set_interface_property slave timingUnits Cycles
set_interface_property slave writeWaitTime 0
set_interface_property slave ENABLED true
set_interface_property slave EXPORT_OF ""
set_interface_property slave PORT_NAME_MAP ""
set_interface_property slave CMSIS_SVD_VARIABLES ""
set_interface_property slave SVD_ADDRESS_GROUP ""

add_interface_port slave avs_slave_address address Input 26
add_interface_port slave avs_slave_read read Input 1
add_interface_port slave avs_slave_readdata readdata Output 128
add_interface_port slave avs_slave_readdatavalid readdatavalid Output 1
add_interface_port slave avs_slave_write write Input 1
add_interface_port slave avs_slave_writedata writedata Input 128
add_interface_port slave avs_slave_waitrequest waitrequest Output 1
add_interface_port slave avs_slave_byteenable byteenable Input 16
add_interface_port slave avs_slave_burstcount burstcount Input 4
add_interface_port slave avs_slave_beginbursttransfer beginbursttransfer Input 1
set_interface_assignment slave embeddedsw.configuration.isFlash 0
set_interface_assignment slave embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment slave embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment slave embeddedsw.configuration.isPrintableDevice 0


# 
# connection point ddr0
# 
add_interface ddr0 avalon start
set_interface_property ddr0 addressUnits WORDS
set_interface_property ddr0 associatedClock clock
set_interface_property ddr0 associatedReset reset
set_interface_property ddr0 bitsPerSymbol 8
set_interface_property ddr0 burstOnBurstBoundariesOnly false
set_interface_property ddr0 burstcountUnits WORDS
set_interface_property ddr0 doStreamReads false
set_interface_property ddr0 doStreamWrites false
set_interface_property ddr0 holdTime 0
set_interface_property ddr0 linewrapBursts false
set_interface_property ddr0 maximumPendingReadTransactions 0
set_interface_property ddr0 maximumPendingWriteTransactions 0
set_interface_property ddr0 readLatency 0
set_interface_property ddr0 readWaitTime 1
set_interface_property ddr0 setupTime 0
set_interface_property ddr0 timingUnits Cycles
set_interface_property ddr0 writeWaitTime 0
set_interface_property ddr0 ENABLED true
set_interface_property ddr0 EXPORT_OF ""
set_interface_property ddr0 PORT_NAME_MAP ""
set_interface_property ddr0 CMSIS_SVD_VARIABLES ""
set_interface_property ddr0 SVD_ADDRESS_GROUP ""

add_interface_port ddr0 avm_ddr0_address address Output 26
add_interface_port ddr0 avm_ddr0_read read Output 1
add_interface_port ddr0 avm_ddr0_readdata readdata Input 64
add_interface_port ddr0 avm_ddr0_readdatavalid readdatavalid Input 1
add_interface_port ddr0 avm_ddr0_write write Output 1
add_interface_port ddr0 avm_ddr0_writedata writedata Output 64
add_interface_port ddr0 avm_ddr0_waitrequest waitrequest Input 1
add_interface_port ddr0 avm_ddr0_byteenable byteenable Output 8
add_interface_port ddr0 avm_ddr0_burstcount burstcount Output 4
add_interface_port ddr0 avm_ddr0_beginbursttransfer beginbursttransfer Output 1


# 
# connection point ddr1
# 
add_interface ddr1 avalon start
set_interface_property ddr1 addressUnits WORDS
set_interface_property ddr1 associatedClock clock
set_interface_property ddr1 associatedReset reset
set_interface_property ddr1 bitsPerSymbol 8
set_interface_property ddr1 burstOnBurstBoundariesOnly false
set_interface_property ddr1 burstcountUnits WORDS
set_interface_property ddr1 doStreamReads false
set_interface_property ddr1 doStreamWrites false
set_interface_property ddr1 holdTime 0
set_interface_property ddr1 linewrapBursts false
set_interface_property ddr1 maximumPendingReadTransactions 0
set_interface_property ddr1 maximumPendingWriteTransactions 0
set_interface_property ddr1 readLatency 0
set_interface_property ddr1 readWaitTime 1
set_interface_property ddr1 setupTime 0
set_interface_property ddr1 timingUnits Cycles
set_interface_property ddr1 writeWaitTime 0
set_interface_property ddr1 ENABLED true
set_interface_property ddr1 EXPORT_OF ""
set_interface_property ddr1 PORT_NAME_MAP ""
set_interface_property ddr1 CMSIS_SVD_VARIABLES ""
set_interface_property ddr1 SVD_ADDRESS_GROUP ""

add_interface_port ddr1 avm_ddr1_address address Output 26
add_interface_port ddr1 avm_ddr1_read read Output 1
add_interface_port ddr1 avm_ddr1_readdata readdata Input 64
add_interface_port ddr1 avm_ddr1_readdatavalid readdatavalid Input 1
add_interface_port ddr1 avm_ddr1_write write Output 1
add_interface_port ddr1 avm_ddr1_writedata writedata Output 64
add_interface_port ddr1 avm_ddr1_waitrequest waitrequest Input 1
add_interface_port ddr1 avm_ddr1_byteenable byteenable Output 8
add_interface_port ddr1 avm_ddr1_burstcount burstcount Output 4
add_interface_port ddr1 avm_ddr1_beginbursttransfer beginbursttransfer Output 1

