# TCL File Generated by Component Editor 18.1
# Thu Sep 16 18:52:51 MSK 2021
# DO NOT MODIFY


# 
# por "por" v18.1
#  2021.09.16.18:52:51
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module por
# 
set_module_property DESCRIPTION ""
set_module_property NAME por
set_module_property VERSION 18.1
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME por
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL por
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file por.sv SYSTEM_VERILOG PATH por.sv
add_fileset_file por.sdc SDC PATH por.sdc


# 
# parameters
# 
add_parameter FAMILY STRING "Cyclone V"
set_parameter_property FAMILY DEFAULT_VALUE "Cyclone V"
set_parameter_property FAMILY DISPLAY_NAME FAMILY
set_parameter_property FAMILY TYPE STRING
set_parameter_property FAMILY UNITS None
set_parameter_property FAMILY HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock_source_1
# 
add_interface clock_source_1 clock start
set_interface_property clock_source_1 associatedDirectClock ""
set_interface_property clock_source_1 clockRate 0
set_interface_property clock_source_1 clockRateKnown false
set_interface_property clock_source_1 ENABLED true
set_interface_property clock_source_1 EXPORT_OF ""
set_interface_property clock_source_1 PORT_NAME_MAP ""
set_interface_property clock_source_1 CMSIS_SVD_VARIABLES ""
set_interface_property clock_source_1 SVD_ADDRESS_GROUP ""

add_interface_port clock_source_1 half_clock clk Output 1


# 
# connection point clock_source_2
# 
add_interface clock_source_2 clock start
set_interface_property clock_source_2 associatedDirectClock ""
set_interface_property clock_source_2 clockRate 0
set_interface_property clock_source_2 clockRateKnown false
set_interface_property clock_source_2 ENABLED true
set_interface_property clock_source_2 EXPORT_OF ""
set_interface_property clock_source_2 PORT_NAME_MAP ""
set_interface_property clock_source_2 CMSIS_SVD_VARIABLES ""
set_interface_property clock_source_2 SVD_ADDRESS_GROUP ""

add_interface_port clock_source_2 quarter_clock clk Output 1


# 
# connection point reset_source
# 
add_interface reset_source reset start
set_interface_property reset_source associatedClock clock_source_0
set_interface_property reset_source associatedDirectReset ""
set_interface_property reset_source associatedResetSinks reset_sink
set_interface_property reset_source synchronousEdges DEASSERT
set_interface_property reset_source ENABLED true
set_interface_property reset_source EXPORT_OF ""
set_interface_property reset_source PORT_NAME_MAP ""
set_interface_property reset_source CMSIS_SVD_VARIABLES ""
set_interface_property reset_source SVD_ADDRESS_GROUP ""

add_interface_port reset_source out_reset_n reset_n Output 1
add_interface_port reset_source out_reset_req reset_req Output 1


# 
# connection point clock_source_0
# 
add_interface clock_source_0 clock start
set_interface_property clock_source_0 associatedDirectClock ""
set_interface_property clock_source_0 clockRate 0
set_interface_property clock_source_0 clockRateKnown false
set_interface_property clock_source_0 ENABLED true
set_interface_property clock_source_0 EXPORT_OF ""
set_interface_property clock_source_0 PORT_NAME_MAP ""
set_interface_property clock_source_0 CMSIS_SVD_VARIABLES ""
set_interface_property clock_source_0 SVD_ADDRESS_GROUP ""

add_interface_port clock_source_0 clock clk Output 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock_source_0
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink reset_n reset_n Input 1

