# TCL File Generated by Component Editor 18.1
# Tue Apr 21 14:19:00 MSK 2020
# DO NOT MODIFY


# 
# A429_Receiver "A429_Receiver" v16.1
#  2020.04.21.14:19:00
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module A429_Receiver
# 
set_module_property DESCRIPTION ""
set_module_property NAME A429_Receiver
set_module_property VERSION 16.1
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME A429_Receiver
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL A429_Receiver
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file AVMM_Master.vhd VHDL PATH ../src/MISC/AVMM_Master.vhd
add_fileset_file RAM.vhd VHDL PATH ../src/MISC/RAM.vhd
add_fileset_file pgen.vhd VHDL PATH ../src/MISC/pgen.vhd
add_fileset_file RingBuffPtr.vhd VHDL PATH ../src/MISC/RingBuffPtr.vhd
add_fileset_file arinc429rx_pkg.vhd VHDL PATH ../src/A429_Receiver/arinc429rx_pkg.vhd
add_fileset_file A429_RxControl.vhd VHDL PATH ../src/A429_Receiver/A429_RxControl.vhd
add_fileset_file a429_RxPhy.vhd VHDL PATH ../src/A429_Receiver/a429_RxPhy.vhd
add_fileset_file A429_Receiver.vhd VHDL PATH ../src/A429_Receiver/A429_Receiver.vhd TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point av2pcie
# 
add_interface av2pcie avalon end
set_interface_property av2pcie addressUnits WORDS
set_interface_property av2pcie associatedClock Avalon_Clock
set_interface_property av2pcie associatedReset Avalon_nReset
set_interface_property av2pcie bitsPerSymbol 8
set_interface_property av2pcie burstOnBurstBoundariesOnly false
set_interface_property av2pcie burstcountUnits WORDS
set_interface_property av2pcie explicitAddressSpan 0
set_interface_property av2pcie holdTime 0
set_interface_property av2pcie linewrapBursts false
set_interface_property av2pcie maximumPendingReadTransactions 1
set_interface_property av2pcie maximumPendingWriteTransactions 0
set_interface_property av2pcie readLatency 0
set_interface_property av2pcie readWaitTime 1
set_interface_property av2pcie setupTime 0
set_interface_property av2pcie timingUnits Cycles
set_interface_property av2pcie writeWaitTime 0
set_interface_property av2pcie ENABLED true
set_interface_property av2pcie EXPORT_OF ""
set_interface_property av2pcie PORT_NAME_MAP ""
set_interface_property av2pcie CMSIS_SVD_VARIABLES ""
set_interface_property av2pcie SVD_ADDRESS_GROUP ""

add_interface_port av2pcie AV2PCIE_waitrequest waitrequest Output 1
add_interface_port av2pcie AV2PCIE_address address Input 12
add_interface_port av2pcie AV2PCIE_byteenable byteenable Input 4
add_interface_port av2pcie AV2PCIE_read read Input 1
add_interface_port av2pcie AV2PCIE_readdata readdata Output 32
add_interface_port av2pcie AV2PCIE_readdatavalid readdatavalid Output 1
add_interface_port av2pcie AV2PCIE_write write Input 1
add_interface_port av2pcie AV2PCIE_writedata writedata Input 32
set_interface_assignment av2pcie embeddedsw.configuration.isFlash 0
set_interface_assignment av2pcie embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment av2pcie embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment av2pcie embeddedsw.configuration.isPrintableDevice 0


# 
# connection point AV2RAM1
# 
add_interface AV2RAM1 avalon start
set_interface_property AV2RAM1 addressUnits WORDS
set_interface_property AV2RAM1 associatedClock Avalon_Clock
set_interface_property AV2RAM1 associatedReset Avalon_nReset
set_interface_property AV2RAM1 bitsPerSymbol 8
set_interface_property AV2RAM1 burstOnBurstBoundariesOnly false
set_interface_property AV2RAM1 burstcountUnits WORDS
set_interface_property AV2RAM1 doStreamReads false
set_interface_property AV2RAM1 doStreamWrites false
set_interface_property AV2RAM1 holdTime 0
set_interface_property AV2RAM1 linewrapBursts false
set_interface_property AV2RAM1 maximumPendingReadTransactions 1
set_interface_property AV2RAM1 maximumPendingWriteTransactions 0
set_interface_property AV2RAM1 readLatency 0
set_interface_property AV2RAM1 readWaitTime 1
set_interface_property AV2RAM1 setupTime 0
set_interface_property AV2RAM1 timingUnits Cycles
set_interface_property AV2RAM1 writeWaitTime 0
set_interface_property AV2RAM1 ENABLED true
set_interface_property AV2RAM1 EXPORT_OF ""
set_interface_property AV2RAM1 PORT_NAME_MAP ""
set_interface_property AV2RAM1 CMSIS_SVD_VARIABLES ""
set_interface_property AV2RAM1 SVD_ADDRESS_GROUP ""

add_interface_port AV2RAM1 AV2RAM_address address Output 12
add_interface_port AV2RAM1 AV2RAM_byteenable byteenable Output 4
add_interface_port AV2RAM1 AV2RAM_read read Output 1
add_interface_port AV2RAM1 AV2RAM_readdata readdata Input 32
add_interface_port AV2RAM1 AV2RAM_readdatavalid readdatavalid Input 1
add_interface_port AV2RAM1 AV2RAM_waitrequest waitrequest Input 1
add_interface_port AV2RAM1 AV2RAM_write write Output 1
add_interface_port AV2RAM1 AV2RAM_writedata writedata Output 32


# 
# connection point AV2RAM2
# 
add_interface AV2RAM2 avalon start
set_interface_property AV2RAM2 addressUnits WORDS
set_interface_property AV2RAM2 associatedClock Avalon_Clock
set_interface_property AV2RAM2 associatedReset Avalon_nReset
set_interface_property AV2RAM2 bitsPerSymbol 8
set_interface_property AV2RAM2 burstOnBurstBoundariesOnly false
set_interface_property AV2RAM2 burstcountUnits WORDS
set_interface_property AV2RAM2 doStreamReads false
set_interface_property AV2RAM2 doStreamWrites false
set_interface_property AV2RAM2 holdTime 0
set_interface_property AV2RAM2 linewrapBursts false
set_interface_property AV2RAM2 maximumPendingReadTransactions 1
set_interface_property AV2RAM2 maximumPendingWriteTransactions 0
set_interface_property AV2RAM2 readLatency 0
set_interface_property AV2RAM2 readWaitTime 1
set_interface_property AV2RAM2 setupTime 0
set_interface_property AV2RAM2 timingUnits Cycles
set_interface_property AV2RAM2 writeWaitTime 0
set_interface_property AV2RAM2 ENABLED true
set_interface_property AV2RAM2 EXPORT_OF ""
set_interface_property AV2RAM2 PORT_NAME_MAP ""
set_interface_property AV2RAM2 CMSIS_SVD_VARIABLES ""
set_interface_property AV2RAM2 SVD_ADDRESS_GROUP ""

add_interface_port AV2RAM2 AV2RAM2_address address Output 12
add_interface_port AV2RAM2 AV2RAM2_byteenable byteenable Output 4
add_interface_port AV2RAM2 AV2RAM2_read read Output 1
add_interface_port AV2RAM2 AV2RAM2_readdata readdata Input 32
add_interface_port AV2RAM2 AV2RAM2_readdatavalid readdatavalid Input 1
add_interface_port AV2RAM2 AV2RAM2_waitrequest waitrequest Input 1
add_interface_port AV2RAM2 AV2RAM2_write write Output 1
add_interface_port AV2RAM2 AV2RAM2_writedata writedata Output 32


# 
# connection point AVS_Config
# 
add_interface AVS_Config avalon end
set_interface_property AVS_Config addressUnits WORDS
set_interface_property AVS_Config associatedClock Avalon_Clock
set_interface_property AVS_Config associatedReset Avalon_nReset
set_interface_property AVS_Config bitsPerSymbol 8
set_interface_property AVS_Config burstOnBurstBoundariesOnly false
set_interface_property AVS_Config burstcountUnits WORDS
set_interface_property AVS_Config explicitAddressSpan 0
set_interface_property AVS_Config holdTime 0
set_interface_property AVS_Config linewrapBursts false
set_interface_property AVS_Config maximumPendingReadTransactions 1
set_interface_property AVS_Config maximumPendingWriteTransactions 0
set_interface_property AVS_Config readLatency 0
set_interface_property AVS_Config readWaitTime 1
set_interface_property AVS_Config setupTime 0
set_interface_property AVS_Config timingUnits Cycles
set_interface_property AVS_Config writeWaitTime 0
set_interface_property AVS_Config ENABLED true
set_interface_property AVS_Config EXPORT_OF ""
set_interface_property AVS_Config PORT_NAME_MAP ""
set_interface_property AVS_Config CMSIS_SVD_VARIABLES ""
set_interface_property AVS_Config SVD_ADDRESS_GROUP ""

add_interface_port AVS_Config AVS_address address Input 5
add_interface_port AVS_Config AVS_byteenable byteenable Input 4
add_interface_port AVS_Config AVS_read read Input 1
add_interface_port AVS_Config AVS_readdata readdata Output 32
add_interface_port AVS_Config AVS_readdatavalid readdatavalid Output 1
add_interface_port AVS_Config AVS_waitrequest waitrequest Output 1
add_interface_port AVS_Config AVS_write write Input 1
add_interface_port AVS_Config AVS_writedata writedata Input 32
set_interface_assignment AVS_Config embeddedsw.configuration.isFlash 0
set_interface_assignment AVS_Config embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment AVS_Config embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment AVS_Config embeddedsw.configuration.isPrintableDevice 0


# 
# connection point Avalon_Clock
# 
add_interface Avalon_Clock clock end
set_interface_property Avalon_Clock clockRate 0
set_interface_property Avalon_Clock ENABLED true
set_interface_property Avalon_Clock EXPORT_OF ""
set_interface_property Avalon_Clock PORT_NAME_MAP ""
set_interface_property Avalon_Clock CMSIS_SVD_VARIABLES ""
set_interface_property Avalon_Clock SVD_ADDRESS_GROUP ""

add_interface_port Avalon_Clock Avalon_Clock clk Input 1


# 
# connection point Avalon_nReset
# 
add_interface Avalon_nReset reset end
set_interface_property Avalon_nReset associatedClock Avalon_Clock
set_interface_property Avalon_nReset synchronousEdges DEASSERT
set_interface_property Avalon_nReset ENABLED true
set_interface_property Avalon_nReset EXPORT_OF ""
set_interface_property Avalon_nReset PORT_NAME_MAP ""
set_interface_property Avalon_nReset CMSIS_SVD_VARIABLES ""
set_interface_property Avalon_nReset SVD_ADDRESS_GROUP ""

add_interface_port Avalon_nReset Avalon_nReset reset_n Input 1


# 
# connection point A429_Clock
# 
add_interface A429_Clock clock end
set_interface_property A429_Clock clockRate 0
set_interface_property A429_Clock ENABLED true
set_interface_property A429_Clock EXPORT_OF ""
set_interface_property A429_Clock PORT_NAME_MAP ""
set_interface_property A429_Clock CMSIS_SVD_VARIABLES ""
set_interface_property A429_Clock SVD_ADDRESS_GROUP ""

add_interface_port A429_Clock A429_Clock clk Input 1


# 
# connection point Interrupt
# 
add_interface Interrupt interrupt end
set_interface_property Interrupt associatedAddressablePoint ""
set_interface_property Interrupt associatedClock Avalon_Clock
set_interface_property Interrupt associatedReset Avalon_nReset
set_interface_property Interrupt bridgedReceiverOffset ""
set_interface_property Interrupt bridgesToReceiver ""
set_interface_property Interrupt ENABLED true
set_interface_property Interrupt EXPORT_OF ""
set_interface_property Interrupt PORT_NAME_MAP ""
set_interface_property Interrupt CMSIS_SVD_VARIABLES ""
set_interface_property Interrupt SVD_ADDRESS_GROUP ""

add_interface_port Interrupt Interrupt irq Output 1


# 
# connection point arinc429
# 
add_interface arinc429 conduit end
set_interface_property arinc429 associatedClock A429_Clock
set_interface_property arinc429 associatedReset ""
set_interface_property arinc429 ENABLED true
set_interface_property arinc429 EXPORT_OF ""
set_interface_property arinc429 PORT_NAME_MAP ""
set_interface_property arinc429 CMSIS_SVD_VARIABLES ""
set_interface_property arinc429 SVD_ADDRESS_GROUP ""

add_interface_port arinc429 A429_LineA a429rx_p Input 1
add_interface_port arinc429 A429_LineB a429rx_n Input 1


# 
# connection point misc
# 
add_interface misc conduit end
set_interface_property misc associatedClock Avalon_Clock
set_interface_property misc associatedReset ""
set_interface_property misc ENABLED true
set_interface_property misc EXPORT_OF ""
set_interface_property misc PORT_NAME_MAP ""
set_interface_property misc CMSIS_SVD_VARIABLES ""
set_interface_property misc SVD_ADDRESS_GROUP ""

add_interface_port misc SentWordIn sentword_in Input 32
add_interface_port misc LineBusy linebusy Output 1


# 
# connection point A429_test
# 
add_interface A429_test conduit end
set_interface_property A429_test associatedClock Avalon_Clock
set_interface_property A429_test associatedReset ""
set_interface_property A429_test ENABLED true
set_interface_property A429_test EXPORT_OF ""
set_interface_property A429_test PORT_NAME_MAP ""
set_interface_property A429_test CMSIS_SVD_VARIABLES ""
set_interface_property A429_test SVD_ADDRESS_GROUP ""

add_interface_port A429_test A429_TestA test_a Output 1
add_interface_port A429_test A429_TestB test_b Output 1
add_interface_port A429_test RxTestEn rxtest_en Output 1

