# TCL File Generated by Component Editor 18.1
# Tue Mar 24 15:11:48 MSK 2020
# DO NOT MODIFY


# 
# A708_Transceiver "A708_Transceiver" v16.1
#  2020.03.24.15:11:48
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module A708_Transceiver
# 
set_module_property DESCRIPTION ""
set_module_property NAME A708_Transceiver
set_module_property VERSION 16.1
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME A708_Transceiver
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL A708_Transceiver
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file FIFO.vhd VHDL PATH ../src/MISC/FIFO.vhd
add_fileset_file pgen.vhd VHDL PATH ../src/MISC/pgen.vhd
add_fileset_file timer.vhd VHDL PATH ../src/MISC/timer.vhd
add_fileset_file AVMM_Master_FIFO.vhd VHDL PATH ../src/MISC/AVMM_Master_FIFO.vhd
add_fileset_file RingBuffPtr.vhd VHDL PATH ../src/MISC/RingBuffPtr.vhd
add_fileset_file a708_pkg.vhd VHDL PATH ../src/A708_Transceiver/a708_pkg.vhd
add_fileset_file A708_Control.vhd VHDL PATH ../src/A708_Transceiver/A708_Control.vhd
add_fileset_file a708_receiver.vhd VHDL PATH ../src/A708_Transceiver/a708_receiver.vhd
add_fileset_file a708_transmitter.vhd VHDL PATH ../src/A708_Transceiver/a708_transmitter.vhd
add_fileset_file A708_Transceiver.vhd VHDL PATH ../src/A708_Transceiver/A708_Transceiver.vhd TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point av2pcie
# 
add_interface av2pcie avalon end
set_interface_property av2pcie addressUnits WORDS
set_interface_property av2pcie associatedClock Avalon_Clk
set_interface_property av2pcie associatedReset Avalon_Reset
set_interface_property av2pcie bitsPerSymbol 8
set_interface_property av2pcie burstOnBurstBoundariesOnly false
set_interface_property av2pcie burstcountUnits WORDS
set_interface_property av2pcie explicitAddressSpan 0
set_interface_property av2pcie holdTime 0
set_interface_property av2pcie linewrapBursts false
set_interface_property av2pcie maximumPendingReadTransactions 1
set_interface_property av2pcie maximumPendingWriteTransactions 0
set_interface_property av2pcie readLatency 0
set_interface_property av2pcie readWaitTime 1
set_interface_property av2pcie setupTime 0
set_interface_property av2pcie timingUnits Cycles
set_interface_property av2pcie writeWaitTime 0
set_interface_property av2pcie ENABLED true
set_interface_property av2pcie EXPORT_OF ""
set_interface_property av2pcie PORT_NAME_MAP ""
set_interface_property av2pcie CMSIS_SVD_VARIABLES ""
set_interface_property av2pcie SVD_ADDRESS_GROUP ""

add_interface_port av2pcie AV2PCIE_waitrequest waitrequest Output 1
add_interface_port av2pcie AV2PCIE_address address Input 10
add_interface_port av2pcie AV2PCIE_byteenable byteenable Input 4
add_interface_port av2pcie AV2PCIE_read read Input 1
add_interface_port av2pcie AV2PCIE_readdata readdata Output 32
add_interface_port av2pcie AV2PCIE_readdatavalid readdatavalid Output 1
add_interface_port av2pcie AV2PCIE_write write Input 1
add_interface_port av2pcie AV2PCIE_writedata writedata Input 32
set_interface_assignment av2pcie embeddedsw.configuration.isFlash 0
set_interface_assignment av2pcie embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment av2pcie embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment av2pcie embeddedsw.configuration.isPrintableDevice 0


# 
# connection point Avalon_Clk
# 
add_interface Avalon_Clk clock end
set_interface_property Avalon_Clk clockRate 0
set_interface_property Avalon_Clk ENABLED true
set_interface_property Avalon_Clk EXPORT_OF ""
set_interface_property Avalon_Clk PORT_NAME_MAP ""
set_interface_property Avalon_Clk CMSIS_SVD_VARIABLES ""
set_interface_property Avalon_Clk SVD_ADDRESS_GROUP ""

add_interface_port Avalon_Clk Avalon_Clock clk Input 1


# 
# connection point Avalon_Reset
# 
add_interface Avalon_Reset reset end
set_interface_property Avalon_Reset associatedClock Avalon_Clk
set_interface_property Avalon_Reset synchronousEdges DEASSERT
set_interface_property Avalon_Reset ENABLED true
set_interface_property Avalon_Reset EXPORT_OF ""
set_interface_property Avalon_Reset PORT_NAME_MAP ""
set_interface_property Avalon_Reset CMSIS_SVD_VARIABLES ""
set_interface_property Avalon_Reset SVD_ADDRESS_GROUP ""

add_interface_port Avalon_Reset Avalon_nReset reset_n Input 1


# 
# connection point AVS_Config
# 
add_interface AVS_Config avalon end
set_interface_property AVS_Config addressUnits WORDS
set_interface_property AVS_Config associatedClock Avalon_Clk
set_interface_property AVS_Config associatedReset Avalon_Reset
set_interface_property AVS_Config bitsPerSymbol 8
set_interface_property AVS_Config burstOnBurstBoundariesOnly false
set_interface_property AVS_Config burstcountUnits WORDS
set_interface_property AVS_Config explicitAddressSpan 0
set_interface_property AVS_Config holdTime 0
set_interface_property AVS_Config linewrapBursts false
set_interface_property AVS_Config maximumPendingReadTransactions 1
set_interface_property AVS_Config maximumPendingWriteTransactions 0
set_interface_property AVS_Config readLatency 0
set_interface_property AVS_Config readWaitTime 1
set_interface_property AVS_Config setupTime 0
set_interface_property AVS_Config timingUnits Cycles
set_interface_property AVS_Config writeWaitTime 0
set_interface_property AVS_Config ENABLED true
set_interface_property AVS_Config EXPORT_OF ""
set_interface_property AVS_Config PORT_NAME_MAP ""
set_interface_property AVS_Config CMSIS_SVD_VARIABLES ""
set_interface_property AVS_Config SVD_ADDRESS_GROUP ""

add_interface_port AVS_Config AVS_waitrequest waitrequest Output 1
add_interface_port AVS_Config AVS_address address Input 2
add_interface_port AVS_Config AVS_byteenable byteenable Input 4
add_interface_port AVS_Config AVS_read read Input 1
add_interface_port AVS_Config AVS_readdata readdata Output 32
add_interface_port AVS_Config AVS_readdatavalid readdatavalid Output 1
add_interface_port AVS_Config AVS_write write Input 1
add_interface_port AVS_Config AVS_writedata writedata Input 32
set_interface_assignment AVS_Config embeddedsw.configuration.isFlash 0
set_interface_assignment AVS_Config embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment AVS_Config embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment AVS_Config embeddedsw.configuration.isPrintableDevice 0


# 
# connection point debug
# 
add_interface debug conduit end
set_interface_property debug associatedClock Avalon_Clk
set_interface_property debug associatedReset ""
set_interface_property debug ENABLED true
set_interface_property debug EXPORT_OF ""
set_interface_property debug PORT_NAME_MAP ""
set_interface_property debug CMSIS_SVD_VARIABLES ""
set_interface_property debug SVD_ADDRESS_GROUP ""

add_interface_port debug NewAvail new_avail Input 1
add_interface_port debug RxCompl rx_compl Output 1


# 
# connection point interrupt
# 
add_interface interrupt interrupt end
set_interface_property interrupt associatedAddressablePoint ""
set_interface_property interrupt associatedClock Avalon_Clk
set_interface_property interrupt associatedReset Avalon_Reset
set_interface_property interrupt bridgedReceiverOffset ""
set_interface_property interrupt bridgesToReceiver ""
set_interface_property interrupt ENABLED true
set_interface_property interrupt EXPORT_OF ""
set_interface_property interrupt PORT_NAME_MAP ""
set_interface_property interrupt CMSIS_SVD_VARIABLES ""
set_interface_property interrupt SVD_ADDRESS_GROUP ""

add_interface_port interrupt Interrupt irq Output 1


# 
# connection point AV2RAM
# 
add_interface AV2RAM avalon start
set_interface_property AV2RAM addressUnits WORDS
set_interface_property AV2RAM associatedClock Avalon_Clk
set_interface_property AV2RAM associatedReset Avalon_Reset
set_interface_property AV2RAM bitsPerSymbol 8
set_interface_property AV2RAM burstOnBurstBoundariesOnly false
set_interface_property AV2RAM burstcountUnits WORDS
set_interface_property AV2RAM doStreamReads false
set_interface_property AV2RAM doStreamWrites false
set_interface_property AV2RAM holdTime 0
set_interface_property AV2RAM linewrapBursts false
set_interface_property AV2RAM maximumPendingReadTransactions 1
set_interface_property AV2RAM maximumPendingWriteTransactions 0
set_interface_property AV2RAM readLatency 0
set_interface_property AV2RAM readWaitTime 1
set_interface_property AV2RAM setupTime 0
set_interface_property AV2RAM timingUnits Cycles
set_interface_property AV2RAM writeWaitTime 0
set_interface_property AV2RAM ENABLED true
set_interface_property AV2RAM EXPORT_OF ""
set_interface_property AV2RAM PORT_NAME_MAP ""
set_interface_property AV2RAM CMSIS_SVD_VARIABLES ""
set_interface_property AV2RAM SVD_ADDRESS_GROUP ""

add_interface_port AV2RAM AV2RAM_address address Output 10
add_interface_port AV2RAM AV2RAM_byteenable byteenable Output 4
add_interface_port AV2RAM AV2RAM_read read Output 1
add_interface_port AV2RAM AV2RAM_readdata readdata Input 32
add_interface_port AV2RAM AV2RAM_readdatavalid readdatavalid Input 1
add_interface_port AV2RAM AV2RAM_waitrequest waitrequest Input 1
add_interface_port AV2RAM AV2RAM_write write Output 1
add_interface_port AV2RAM AV2RAM_writedata writedata Output 32


# 
# connection point AV2RAM2
# 
add_interface AV2RAM2 avalon start
set_interface_property AV2RAM2 addressUnits WORDS
set_interface_property AV2RAM2 associatedClock Avalon_Clk
set_interface_property AV2RAM2 associatedReset Avalon_Reset
set_interface_property AV2RAM2 bitsPerSymbol 8
set_interface_property AV2RAM2 burstOnBurstBoundariesOnly false
set_interface_property AV2RAM2 burstcountUnits WORDS
set_interface_property AV2RAM2 doStreamReads false
set_interface_property AV2RAM2 doStreamWrites false
set_interface_property AV2RAM2 holdTime 0
set_interface_property AV2RAM2 linewrapBursts false
set_interface_property AV2RAM2 maximumPendingReadTransactions 1
set_interface_property AV2RAM2 maximumPendingWriteTransactions 0
set_interface_property AV2RAM2 readLatency 0
set_interface_property AV2RAM2 readWaitTime 1
set_interface_property AV2RAM2 setupTime 0
set_interface_property AV2RAM2 timingUnits Cycles
set_interface_property AV2RAM2 writeWaitTime 0
set_interface_property AV2RAM2 ENABLED true
set_interface_property AV2RAM2 EXPORT_OF ""
set_interface_property AV2RAM2 PORT_NAME_MAP ""
set_interface_property AV2RAM2 CMSIS_SVD_VARIABLES ""
set_interface_property AV2RAM2 SVD_ADDRESS_GROUP ""

add_interface_port AV2RAM2 AV2RAM2_waitrequest waitrequest Input 1
add_interface_port AV2RAM2 AV2RAM2_address address Output 10
add_interface_port AV2RAM2 AV2RAM2_byteenable byteenable Output 4
add_interface_port AV2RAM2 AV2RAM2_read read Output 1
add_interface_port AV2RAM2 AV2RAM2_readdata readdata Input 32
add_interface_port AV2RAM2 AV2RAM2_readdatavalid readdatavalid Input 1
add_interface_port AV2RAM2 AV2RAM2_write write Output 1
add_interface_port AV2RAM2 AV2RAM2_writedata writedata Output 32


# 
# connection point arinc708
# 
add_interface arinc708 conduit end
set_interface_property arinc708 associatedClock Avalon_Clk
set_interface_property arinc708 associatedReset ""
set_interface_property arinc708 ENABLED true
set_interface_property arinc708 EXPORT_OF ""
set_interface_property arinc708 PORT_NAME_MAP ""
set_interface_property arinc708 CMSIS_SVD_VARIABLES ""
set_interface_property arinc708 SVD_ADDRESS_GROUP ""

add_interface_port arinc708 TxInhibit a708_tx_inh Output 1
add_interface_port arinc708 OutputA a708_tx_p Output 1
add_interface_port arinc708 OutputB a708_tx_n Output 1
add_interface_port arinc708 LineTurnOFF line_turnoff Output 1
add_interface_port arinc708 RxEn a708_rxen Output 1
add_interface_port arinc708 inputA a708_rx_p Input 1
add_interface_port arinc708 inputB a708_rx_n Input 1


# 
# connection point arinc708_clock
# 
add_interface arinc708_clock clock end
set_interface_property arinc708_clock clockRate 0
set_interface_property arinc708_clock ENABLED true
set_interface_property arinc708_clock EXPORT_OF ""
set_interface_property arinc708_clock PORT_NAME_MAP ""
set_interface_property arinc708_clock CMSIS_SVD_VARIABLES ""
set_interface_property arinc708_clock SVD_ADDRESS_GROUP ""

add_interface_port arinc708_clock A708_Clock clk Input 1

