# TCL File Generated by Component Editor 18.1
# Tue Mar 16 15:42:07 MSK 2021
# DO NOT MODIFY


# 
# ams_i2c "ams_i2c" v18.0
#  2021.03.16.15:42:07
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module ams_i2c
# 
set_module_property DESCRIPTION ""
set_module_property NAME ams_i2c
set_module_property VERSION 18.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME ams_i2c
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL ams_i2c
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file ams_i2c.sv SYSTEM_VERILOG PATH ../src/ams_i2c.sv TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter clock_freq INTEGER 0 CLOCK_RATE
set_parameter_property clock_freq DEFAULT_VALUE 0
set_parameter_property clock_freq DISPLAY_NAME clock_freq
set_parameter_property clock_freq TYPE INTEGER
set_parameter_property clock_freq UNITS Hertz
set_parameter_property clock_freq ALLOWED_RANGES 0:250000000
set_parameter_property clock_freq DESCRIPTION CLOCK_RATE
set_parameter_property clock_freq HDL_PARAMETER true
set_parameter_property clock_freq SYSTEM_INFO_TYPE CLOCK_RATE
set_parameter_property clock_freq SYSTEM_INFO_ARG clock_sink
add_parameter baudrate INTEGER 100000
set_parameter_property baudrate DEFAULT_VALUE 100000
set_parameter_property baudrate DISPLAY_NAME baudrate
set_parameter_property baudrate TYPE INTEGER
set_parameter_property baudrate UNITS Hertz
set_parameter_property baudrate ALLOWED_RANGES 0:400000
set_parameter_property baudrate HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock_sink
# 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0
set_interface_property clock_sink ENABLED true
set_interface_property clock_sink EXPORT_OF ""
set_interface_property clock_sink PORT_NAME_MAP ""
set_interface_property clock_sink CMSIS_SVD_VARIABLES ""
set_interface_property clock_sink SVD_ADDRESS_GROUP ""

add_interface_port clock_sink clock clk Input 1


# 
# connection point i2c_bus
# 
add_interface i2c_bus conduit end
set_interface_property i2c_bus associatedClock ""
set_interface_property i2c_bus associatedReset ""
set_interface_property i2c_bus ENABLED true
set_interface_property i2c_bus EXPORT_OF ""
set_interface_property i2c_bus PORT_NAME_MAP ""
set_interface_property i2c_bus CMSIS_SVD_VARIABLES ""
set_interface_property i2c_bus SVD_ADDRESS_GROUP ""

add_interface_port i2c_bus scl clk Bidir 1
add_interface_port i2c_bus sda data Bidir 1


# 
# connection point ams
# 
add_interface ams avalon end
set_interface_property ams addressUnits WORDS
set_interface_property ams associatedClock clock_sink
set_interface_property ams associatedReset reset_sink
set_interface_property ams bitsPerSymbol 8
set_interface_property ams burstOnBurstBoundariesOnly false
set_interface_property ams burstcountUnits WORDS
set_interface_property ams explicitAddressSpan 0
set_interface_property ams holdTime 0
set_interface_property ams linewrapBursts false
set_interface_property ams maximumPendingReadTransactions 1
set_interface_property ams maximumPendingWriteTransactions 0
set_interface_property ams readLatency 0
set_interface_property ams readWaitTime 1
set_interface_property ams setupTime 0
set_interface_property ams timingUnits Cycles
set_interface_property ams writeWaitTime 0
set_interface_property ams ENABLED true
set_interface_property ams EXPORT_OF ""
set_interface_property ams PORT_NAME_MAP ""
set_interface_property ams CMSIS_SVD_VARIABLES ""
set_interface_property ams SVD_ADDRESS_GROUP ""

add_interface_port ams ams_waitrequest waitrequest Output 1
add_interface_port ams ams_write write Input 1
add_interface_port ams ams_read read Input 1
add_interface_port ams ams_address address Input 16
add_interface_port ams ams_writedata writedata Input 8
add_interface_port ams ams_readdatavalid readdatavalid Output 1
add_interface_port ams ams_readdata readdata Output 8
add_interface_port ams ams_response response Output 2
set_interface_assignment ams embeddedsw.configuration.isFlash 0
set_interface_assignment ams embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment ams embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment ams embeddedsw.configuration.isPrintableDevice 0


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock_sink
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink reset_n reset_n Input 1

