# TCL File Generated by Component Editor 18.1
# Sun Apr 19 17:48:56 MSK 2020
# DO NOT MODIFY


# 
# ddr_reset "ddr_reset" v18.1
#  2020.04.19.17:48:56
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module ddr_reset
# 
set_module_property DESCRIPTION ""
set_module_property NAME ddr_reset
set_module_property VERSION 18.1
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME ddr_reset
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL ddr_reset
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file ddr_reset.v VERILOG PATH ../src/ddr_reset.v TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter GLOBAL_RESET_TIME INTEGER 800000
set_parameter_property GLOBAL_RESET_TIME DEFAULT_VALUE 800000
set_parameter_property GLOBAL_RESET_TIME DISPLAY_NAME GLOBAL_RESET_TIME
set_parameter_property GLOBAL_RESET_TIME TYPE INTEGER
set_parameter_property GLOBAL_RESET_TIME UNITS None
set_parameter_property GLOBAL_RESET_TIME ALLOWED_RANGES -2147483648:2147483647
set_parameter_property GLOBAL_RESET_TIME HDL_PARAMETER true
add_parameter SOFT_RESET_TIME INTEGER 800000
set_parameter_property SOFT_RESET_TIME DEFAULT_VALUE 800000
set_parameter_property SOFT_RESET_TIME DISPLAY_NAME SOFT_RESET_TIME
set_parameter_property SOFT_RESET_TIME TYPE INTEGER
set_parameter_property SOFT_RESET_TIME UNITS None
set_parameter_property SOFT_RESET_TIME ALLOWED_RANGES -2147483648:2147483647
set_parameter_property SOFT_RESET_TIME HDL_PARAMETER true
add_parameter READY_TIME INTEGER 800000 ""
set_parameter_property READY_TIME DEFAULT_VALUE 800000
set_parameter_property READY_TIME DISPLAY_NAME READY_TIME
set_parameter_property READY_TIME TYPE INTEGER
set_parameter_property READY_TIME UNITS None
set_parameter_property READY_TIME ALLOWED_RANGES -2147483648:2147483647
set_parameter_property READY_TIME DESCRIPTION ""
set_parameter_property READY_TIME HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point ddr_pll
# 
add_interface ddr_pll conduit end
set_interface_property ddr_pll associatedClock ""
set_interface_property ddr_pll associatedReset ""
set_interface_property ddr_pll ENABLED true
set_interface_property ddr_pll EXPORT_OF ""
set_interface_property ddr_pll PORT_NAME_MAP ""
set_interface_property ddr_pll CMSIS_SVD_VARIABLES ""
set_interface_property ddr_pll SVD_ADDRESS_GROUP ""

add_interface_port ddr_pll pll_mem_clk pll_mem_clk Input 1
add_interface_port ddr_pll pll_locked pll_locked Input 1
add_interface_port ddr_pll pll_addr_cmd_clk pll_addr_cmd_clk Input 1
add_interface_port ddr_pll pll_avl_clk pll_avl_clk Input 1
add_interface_port ddr_pll pll_config_clk pll_config_clk Input 1
add_interface_port ddr_pll pll_mem_phy_clk pll_mem_phy_clk Input 1
add_interface_port ddr_pll afi_phy_clk afi_phy_clk Input 1
add_interface_port ddr_pll pll_avl_phy_clk pll_avl_phy_clk Input 1
add_interface_port ddr_pll pll_write_clk pll_write_clk Input 1
add_interface_port ddr_pll pll_write_clk_pre_phy_clk pll_write_clk_pre_phy_clk Input 1


# 
# connection point ddr_status
# 
add_interface ddr_status conduit end
set_interface_property ddr_status associatedClock ""
set_interface_property ddr_status associatedReset ""
set_interface_property ddr_status ENABLED true
set_interface_property ddr_status EXPORT_OF ""
set_interface_property ddr_status PORT_NAME_MAP ""
set_interface_property ddr_status CMSIS_SVD_VARIABLES ""
set_interface_property ddr_status SVD_ADDRESS_GROUP ""

add_interface_port ddr_status local_cal_fail local_cal_fail Input 1
add_interface_port ddr_status local_cal_success local_cal_success Input 1
add_interface_port ddr_status local_init_done local_init_done Input 1


# 
# connection point global_reset
# 
add_interface global_reset reset start
set_interface_property global_reset associatedClock ""
set_interface_property global_reset associatedDirectReset ""
set_interface_property global_reset associatedResetSinks ""
set_interface_property global_reset synchronousEdges NONE
set_interface_property global_reset ENABLED true
set_interface_property global_reset EXPORT_OF ""
set_interface_property global_reset PORT_NAME_MAP ""
set_interface_property global_reset CMSIS_SVD_VARIABLES ""
set_interface_property global_reset SVD_ADDRESS_GROUP ""

add_interface_port global_reset gl_reset_n reset_n Output 1


# 
# connection point ready
# 
add_interface ready reset start
set_interface_property ready associatedClock ""
set_interface_property ready associatedDirectReset ""
set_interface_property ready associatedResetSinks ""
set_interface_property ready synchronousEdges NONE
set_interface_property ready ENABLED true
set_interface_property ready EXPORT_OF ""
set_interface_property ready PORT_NAME_MAP ""
set_interface_property ready CMSIS_SVD_VARIABLES ""
set_interface_property ready SVD_ADDRESS_GROUP ""

add_interface_port ready ready reset_n Output 1


# 
# connection point soft_reset
# 
add_interface soft_reset reset start
set_interface_property soft_reset associatedClock ""
set_interface_property soft_reset associatedDirectReset ""
set_interface_property soft_reset associatedResetSinks ""
set_interface_property soft_reset synchronousEdges NONE
set_interface_property soft_reset ENABLED true
set_interface_property soft_reset EXPORT_OF ""
set_interface_property soft_reset PORT_NAME_MAP ""
set_interface_property soft_reset CMSIS_SVD_VARIABLES ""
set_interface_property soft_reset SVD_ADDRESS_GROUP ""

add_interface_port soft_reset sw_reset_n reset_n Output 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock ""
set_interface_property reset synchronousEdges NONE
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1

