# TCL File Generated by Component Editor 18.1
# Thu May 20 10:17:54 MSK 2021
# DO NOT MODIFY


# 
# I2C_Transceiver "I2C_Transceiver" v16.1
#  2021.05.20.10:17:54
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module I2C_Transceiver
# 
set_module_property DESCRIPTION ""
set_module_property NAME I2C_Transceiver
set_module_property VERSION 16.1
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME I2C_Transceiver
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL i2c_transceiver
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file timer.vhd VHDL PATH ../src/MISC/timer.vhd
add_fileset_file PWM_Gen16.vhd VHDL PATH ../src/MISC/PWM_Gen16.vhd
add_fileset_file pgen.vhd VHDL PATH ../src/MISC/pgen.vhd
add_fileset_file AVMM_Master.vhd VHDL PATH ../src/MISC/AVMM_Master.vhd
add_fileset_file i2c_pkg.vhd VHDL PATH ../src/I2C_Transceiver/i2c_pkg.vhd
add_fileset_file key_codes_pkg.vhd VHDL PATH ../src/I2C_Transceiver/key_codes_pkg.vhd
add_fileset_file recalc.sv SYSTEM_VERILOG PATH ../src/I2C_Transceiver/recalc.sv
add_fileset_file i2c_control.vhd VHDL PATH ../src/I2C_Transceiver/i2c_control.vhd
add_fileset_file i2c_master.vhd VHDL PATH ../src/I2C_Transceiver/i2c_master.vhd
add_fileset_file i2c_transceiver.vhd VHDL PATH ../src/I2C_Transceiver/i2c_transceiver.vhd TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point av2pcie
# 
add_interface av2pcie avalon end
set_interface_property av2pcie addressUnits WORDS
set_interface_property av2pcie associatedClock Avalon_Clk
set_interface_property av2pcie associatedReset Avalon_nReset
set_interface_property av2pcie bitsPerSymbol 8
set_interface_property av2pcie burstOnBurstBoundariesOnly false
set_interface_property av2pcie burstcountUnits WORDS
set_interface_property av2pcie explicitAddressSpan 0
set_interface_property av2pcie holdTime 0
set_interface_property av2pcie linewrapBursts false
set_interface_property av2pcie maximumPendingReadTransactions 1
set_interface_property av2pcie maximumPendingWriteTransactions 0
set_interface_property av2pcie readLatency 0
set_interface_property av2pcie readWaitTime 1
set_interface_property av2pcie setupTime 0
set_interface_property av2pcie timingUnits Cycles
set_interface_property av2pcie writeWaitTime 0
set_interface_property av2pcie ENABLED true
set_interface_property av2pcie EXPORT_OF ""
set_interface_property av2pcie PORT_NAME_MAP ""
set_interface_property av2pcie CMSIS_SVD_VARIABLES ""
set_interface_property av2pcie SVD_ADDRESS_GROUP ""

add_interface_port av2pcie AV2PCIE_waitrequest waitrequest Output 1
add_interface_port av2pcie AV2PCIE_address address Input 6
add_interface_port av2pcie AV2PCIE_byteenable byteenable Input 4
add_interface_port av2pcie AV2PCIE_read read Input 1
add_interface_port av2pcie AV2PCIE_readdata readdata Output 32
add_interface_port av2pcie AV2PCIE_readdatavalid readdatavalid Output 1
add_interface_port av2pcie AV2PCIE_write write Input 1
add_interface_port av2pcie AV2PCIE_writedata writedata Input 32
set_interface_assignment av2pcie embeddedsw.configuration.isFlash 0
set_interface_assignment av2pcie embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment av2pcie embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment av2pcie embeddedsw.configuration.isPrintableDevice 0


# 
# connection point Avalon_Clk
# 
add_interface Avalon_Clk clock end
set_interface_property Avalon_Clk clockRate 0
set_interface_property Avalon_Clk ENABLED true
set_interface_property Avalon_Clk EXPORT_OF ""
set_interface_property Avalon_Clk PORT_NAME_MAP ""
set_interface_property Avalon_Clk CMSIS_SVD_VARIABLES ""
set_interface_property Avalon_Clk SVD_ADDRESS_GROUP ""

add_interface_port Avalon_Clk Avalon_Clock clk Input 1


# 
# connection point Avalon_nReset
# 
add_interface Avalon_nReset reset end
set_interface_property Avalon_nReset associatedClock Avalon_Clk
set_interface_property Avalon_nReset synchronousEdges DEASSERT
set_interface_property Avalon_nReset ENABLED true
set_interface_property Avalon_nReset EXPORT_OF ""
set_interface_property Avalon_nReset PORT_NAME_MAP ""
set_interface_property Avalon_nReset CMSIS_SVD_VARIABLES ""
set_interface_property Avalon_nReset SVD_ADDRESS_GROUP ""

add_interface_port Avalon_nReset Avalon_nReset reset_n Input 1


# 
# connection point AV2RAM
# 
add_interface AV2RAM avalon start
set_interface_property AV2RAM addressUnits WORDS
set_interface_property AV2RAM associatedClock Avalon_Clk
set_interface_property AV2RAM associatedReset Avalon_nReset
set_interface_property AV2RAM bitsPerSymbol 8
set_interface_property AV2RAM burstOnBurstBoundariesOnly false
set_interface_property AV2RAM burstcountUnits WORDS
set_interface_property AV2RAM doStreamReads false
set_interface_property AV2RAM doStreamWrites false
set_interface_property AV2RAM holdTime 0
set_interface_property AV2RAM linewrapBursts false
set_interface_property AV2RAM maximumPendingReadTransactions 1
set_interface_property AV2RAM maximumPendingWriteTransactions 0
set_interface_property AV2RAM readLatency 0
set_interface_property AV2RAM readWaitTime 1
set_interface_property AV2RAM setupTime 0
set_interface_property AV2RAM timingUnits Cycles
set_interface_property AV2RAM writeWaitTime 0
set_interface_property AV2RAM ENABLED true
set_interface_property AV2RAM EXPORT_OF ""
set_interface_property AV2RAM PORT_NAME_MAP ""
set_interface_property AV2RAM CMSIS_SVD_VARIABLES ""
set_interface_property AV2RAM SVD_ADDRESS_GROUP ""

add_interface_port AV2RAM AV2RAM_address address Output 6
add_interface_port AV2RAM AV2RAM_byteenable byteenable Output 4
add_interface_port AV2RAM AV2RAM_read read Output 1
add_interface_port AV2RAM AV2RAM_readdata readdata Input 32
add_interface_port AV2RAM AV2RAM_readdatavalid readdatavalid Input 1
add_interface_port AV2RAM AV2RAM_waitrequest waitrequest Input 1
add_interface_port AV2RAM AV2RAM_write write Output 1
add_interface_port AV2RAM AV2RAM_writedata writedata Output 32


# 
# connection point AV2RAM2
# 
add_interface AV2RAM2 avalon start
set_interface_property AV2RAM2 addressUnits WORDS
set_interface_property AV2RAM2 associatedClock Avalon_Clk
set_interface_property AV2RAM2 associatedReset Avalon_nReset
set_interface_property AV2RAM2 bitsPerSymbol 8
set_interface_property AV2RAM2 burstOnBurstBoundariesOnly false
set_interface_property AV2RAM2 burstcountUnits WORDS
set_interface_property AV2RAM2 doStreamReads false
set_interface_property AV2RAM2 doStreamWrites false
set_interface_property AV2RAM2 holdTime 0
set_interface_property AV2RAM2 linewrapBursts false
set_interface_property AV2RAM2 maximumPendingReadTransactions 1
set_interface_property AV2RAM2 maximumPendingWriteTransactions 0
set_interface_property AV2RAM2 readLatency 0
set_interface_property AV2RAM2 readWaitTime 1
set_interface_property AV2RAM2 setupTime 0
set_interface_property AV2RAM2 timingUnits Cycles
set_interface_property AV2RAM2 writeWaitTime 0
set_interface_property AV2RAM2 ENABLED true
set_interface_property AV2RAM2 EXPORT_OF ""
set_interface_property AV2RAM2 PORT_NAME_MAP ""
set_interface_property AV2RAM2 CMSIS_SVD_VARIABLES ""
set_interface_property AV2RAM2 SVD_ADDRESS_GROUP ""

add_interface_port AV2RAM2 AV2RAM2_address address Output 6
add_interface_port AV2RAM2 AV2RAM2_byteenable byteenable Output 4
add_interface_port AV2RAM2 AV2RAM2_read read Output 1
add_interface_port AV2RAM2 AV2RAM2_readdata readdata Input 32
add_interface_port AV2RAM2 AV2RAM2_readdatavalid readdatavalid Input 1
add_interface_port AV2RAM2 AV2RAM2_waitrequest waitrequest Input 1
add_interface_port AV2RAM2 AV2RAM2_write write Output 1
add_interface_port AV2RAM2 AV2RAM2_writedata writedata Output 32


# 
# connection point AVS_Config
# 
add_interface AVS_Config avalon end
set_interface_property AVS_Config addressUnits WORDS
set_interface_property AVS_Config associatedClock Avalon_Clk
set_interface_property AVS_Config associatedReset Avalon_nReset
set_interface_property AVS_Config bitsPerSymbol 8
set_interface_property AVS_Config burstOnBurstBoundariesOnly false
set_interface_property AVS_Config burstcountUnits WORDS
set_interface_property AVS_Config explicitAddressSpan 0
set_interface_property AVS_Config holdTime 0
set_interface_property AVS_Config linewrapBursts false
set_interface_property AVS_Config maximumPendingReadTransactions 1
set_interface_property AVS_Config maximumPendingWriteTransactions 0
set_interface_property AVS_Config readLatency 0
set_interface_property AVS_Config readWaitTime 1
set_interface_property AVS_Config setupTime 0
set_interface_property AVS_Config timingUnits Cycles
set_interface_property AVS_Config writeWaitTime 0
set_interface_property AVS_Config ENABLED true
set_interface_property AVS_Config EXPORT_OF ""
set_interface_property AVS_Config PORT_NAME_MAP ""
set_interface_property AVS_Config CMSIS_SVD_VARIABLES ""
set_interface_property AVS_Config SVD_ADDRESS_GROUP ""

add_interface_port AVS_Config AVS_waitrequest waitrequest Output 1
add_interface_port AVS_Config AVS_address address Input 3
add_interface_port AVS_Config AVS_byteenable byteenable Input 4
add_interface_port AVS_Config AVS_read read Input 1
add_interface_port AVS_Config AVS_readdata readdata Output 32
add_interface_port AVS_Config AVS_readdatavalid readdatavalid Output 1
add_interface_port AVS_Config AVS_write write Input 1
add_interface_port AVS_Config AVS_writedata writedata Input 32
set_interface_assignment AVS_Config embeddedsw.configuration.isFlash 0
set_interface_assignment AVS_Config embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment AVS_Config embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment AVS_Config embeddedsw.configuration.isPrintableDevice 0


# 
# connection point I2C_SCL
# 
add_interface I2C_SCL conduit end
set_interface_property I2C_SCL associatedClock ""
set_interface_property I2C_SCL associatedReset Avalon_nReset
set_interface_property I2C_SCL ENABLED true
set_interface_property I2C_SCL EXPORT_OF ""
set_interface_property I2C_SCL PORT_NAME_MAP ""
set_interface_property I2C_SCL CMSIS_SVD_VARIABLES ""
set_interface_property I2C_SCL SVD_ADDRESS_GROUP ""

add_interface_port I2C_SCL SCL scl Bidir 1


# 
# connection point I2C_Clk
# 
add_interface I2C_Clk clock end
set_interface_property I2C_Clk clockRate 0
set_interface_property I2C_Clk ENABLED true
set_interface_property I2C_Clk EXPORT_OF ""
set_interface_property I2C_Clk PORT_NAME_MAP ""
set_interface_property I2C_Clk CMSIS_SVD_VARIABLES ""
set_interface_property I2C_Clk SVD_ADDRESS_GROUP ""

add_interface_port I2C_Clk i2c_Clk clk Input 1


# 
# connection point I2C_SDA
# 
add_interface I2C_SDA conduit end
set_interface_property I2C_SDA associatedClock I2C_Clk
set_interface_property I2C_SDA associatedReset Avalon_nReset
set_interface_property I2C_SDA ENABLED true
set_interface_property I2C_SDA EXPORT_OF ""
set_interface_property I2C_SDA PORT_NAME_MAP ""
set_interface_property I2C_SDA CMSIS_SVD_VARIABLES ""
set_interface_property I2C_SDA SVD_ADDRESS_GROUP ""

add_interface_port I2C_SDA SDA sda Bidir 1


# 
# connection point LCD_PWM
# 
add_interface LCD_PWM conduit end
set_interface_property LCD_PWM associatedClock Avalon_Clk
set_interface_property LCD_PWM associatedReset ""
set_interface_property LCD_PWM ENABLED true
set_interface_property LCD_PWM EXPORT_OF ""
set_interface_property LCD_PWM PORT_NAME_MAP ""
set_interface_property LCD_PWM CMSIS_SVD_VARIABLES ""
set_interface_property LCD_PWM SVD_ADDRESS_GROUP ""

add_interface_port LCD_PWM LCD_BKLT_PWM pwm Output 1
add_interface_port LCD_PWM LCD_BKLT_FLT flt Input 1


# 
# connection point BTN_PWM
# 
add_interface BTN_PWM conduit end
set_interface_property BTN_PWM associatedClock Avalon_Clk
set_interface_property BTN_PWM associatedReset ""
set_interface_property BTN_PWM ENABLED true
set_interface_property BTN_PWM EXPORT_OF ""
set_interface_property BTN_PWM PORT_NAME_MAP ""
set_interface_property BTN_PWM CMSIS_SVD_VARIABLES ""
set_interface_property BTN_PWM SVD_ADDRESS_GROUP ""

add_interface_port BTN_PWM BTN_BKLT_PWM pwm Output 1


# 
# connection point SPIN_PWM
# 
add_interface SPIN_PWM conduit end
set_interface_property SPIN_PWM associatedClock Avalon_Clk
set_interface_property SPIN_PWM associatedReset ""
set_interface_property SPIN_PWM ENABLED true
set_interface_property SPIN_PWM EXPORT_OF ""
set_interface_property SPIN_PWM PORT_NAME_MAP ""
set_interface_property SPIN_PWM CMSIS_SVD_VARIABLES ""
set_interface_property SPIN_PWM SVD_ADDRESS_GROUP ""

add_interface_port SPIN_PWM SPIN_BKLT_PWM pwm Output 1


# 
# connection point nout_en
# 
add_interface nout_en conduit end
set_interface_property nout_en associatedClock I2C_Clk
set_interface_property nout_en associatedReset Avalon_nReset
set_interface_property nout_en ENABLED true
set_interface_property nout_en EXPORT_OF ""
set_interface_property nout_en PORT_NAME_MAP ""
set_interface_property nout_en CMSIS_SVD_VARIABLES ""
set_interface_property nout_en SVD_ADDRESS_GROUP ""

add_interface_port nout_en nOUT_EN nout_en Output 2


# 
# connection point BKLT_EN
# 
add_interface BKLT_EN conduit end
set_interface_property BKLT_EN associatedClock Avalon_Clk
set_interface_property BKLT_EN associatedReset Avalon_nReset
set_interface_property BKLT_EN ENABLED true
set_interface_property BKLT_EN EXPORT_OF ""
set_interface_property BKLT_EN PORT_NAME_MAP ""
set_interface_property BKLT_EN CMSIS_SVD_VARIABLES ""
set_interface_property BKLT_EN SVD_ADDRESS_GROUP ""

add_interface_port BKLT_EN LCD_BKLT_EN1 en1 Output 1
add_interface_port BKLT_EN LCD_BKLT_EN2 en2 Output 1


# 
# connection point day_night
# 
add_interface day_night conduit end
set_interface_property day_night associatedClock Avalon_Clk
set_interface_property day_night associatedReset Avalon_nReset
set_interface_property day_night ENABLED true
set_interface_property day_night EXPORT_OF ""
set_interface_property day_night PORT_NAME_MAP ""
set_interface_property day_night CMSIS_SVD_VARIABLES ""
set_interface_property day_night SVD_ADDRESS_GROUP ""

add_interface_port day_night DayNightBright day_night Input 1


# 
# connection point lcd_size
# 
add_interface lcd_size conduit end
set_interface_property lcd_size associatedClock ""
set_interface_property lcd_size associatedReset ""
set_interface_property lcd_size ENABLED true
set_interface_property lcd_size EXPORT_OF ""
set_interface_property lcd_size PORT_NAME_MAP ""
set_interface_property lcd_size CMSIS_SVD_VARIABLES ""
set_interface_property lcd_size SVD_ADDRESS_GROUP ""

add_interface_port lcd_size LCD_Size_Code code Output 2

