# TCL File Generated by Component Editor 18.1
# Tue Mar 24 15:12:19 MSK 2020
# DO NOT MODIFY


# 
# lcd_heater "lcd_heater" v16.1
#  2020.03.24.15:12:19
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module lcd_heater
# 
set_module_property DESCRIPTION ""
set_module_property NAME lcd_heater
set_module_property VERSION 16.1
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME lcd_heater
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL lcd_heater
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file i2c_heater_pkg.vhd VHDL PATH ../src/lcd_heater/i2c_heater_pkg.vhd
add_fileset_file lcd_heater_pkg.vhd VHDL PATH ../src/lcd_heater/lcd_heater_pkg.vhd
add_fileset_file PWM_Gen16.vhd VHDL PATH ../src/MISC/PWM_Gen16.vhd
add_fileset_file timer.vhd VHDL PATH ../src/MISC/timer.vhd
add_fileset_file pgen.vhd VHDL PATH ../src/MISC/pgen.vhd
add_fileset_file pulse_stretch.vhd VHDL PATH ../src/MISC/pulse_stretch.vhd
add_fileset_file i2c_master_heater.vhd VHDL PATH ../src/lcd_heater/i2c_master_heater.vhd
add_fileset_file pid_heater.vhd VHDL PATH ../src/lcd_heater/pid_heater.vhd
add_fileset_file lcd_heater.vhd VHDL PATH ../src/lcd_heater/lcd_heater.vhd TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock Clk
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset Avalon_nReset reset_n Input 1


# 
# connection point Clk
# 
add_interface Clk clock end
set_interface_property Clk clockRate 0
set_interface_property Clk ENABLED true
set_interface_property Clk EXPORT_OF ""
set_interface_property Clk PORT_NAME_MAP ""
set_interface_property Clk CMSIS_SVD_VARIABLES ""
set_interface_property Clk SVD_ADDRESS_GROUP ""

add_interface_port Clk Avalon_Clock clk Input 1


# 
# connection point i2c
# 
add_interface i2c conduit end
set_interface_property i2c associatedClock Clk
set_interface_property i2c associatedReset ""
set_interface_property i2c ENABLED true
set_interface_property i2c EXPORT_OF ""
set_interface_property i2c PORT_NAME_MAP ""
set_interface_property i2c CMSIS_SVD_VARIABLES ""
set_interface_property i2c SVD_ADDRESS_GROUP ""

add_interface_port i2c I2C_SCL scl Bidir 1
add_interface_port i2c I2C_SDA sda Bidir 1


# 
# connection point pwm
# 
add_interface pwm conduit end
set_interface_property pwm associatedClock Clk
set_interface_property pwm associatedReset ""
set_interface_property pwm ENABLED true
set_interface_property pwm EXPORT_OF ""
set_interface_property pwm PORT_NAME_MAP ""
set_interface_property pwm CMSIS_SVD_VARIABLES ""
set_interface_property pwm SVD_ADDRESS_GROUP ""

add_interface_port pwm LCD_HEAT pwm_out Output 1


# 
# connection point CurSensorIn
# 
add_interface CurSensorIn conduit end
set_interface_property CurSensorIn associatedClock Clk
set_interface_property CurSensorIn associatedReset ""
set_interface_property CurSensorIn ENABLED true
set_interface_property CurSensorIn EXPORT_OF ""
set_interface_property CurSensorIn PORT_NAME_MAP ""
set_interface_property CurSensorIn CMSIS_SVD_VARIABLES ""
set_interface_property CurSensorIn SVD_ADDRESS_GROUP ""

add_interface_port CurSensorIn nHEAT_CUR_SENS cur_sens Input 1


# 
# connection point AVS_Config
# 
add_interface AVS_Config avalon end
set_interface_property AVS_Config addressUnits WORDS
set_interface_property AVS_Config associatedClock Clk
set_interface_property AVS_Config associatedReset reset
set_interface_property AVS_Config bitsPerSymbol 8
set_interface_property AVS_Config burstOnBurstBoundariesOnly false
set_interface_property AVS_Config burstcountUnits WORDS
set_interface_property AVS_Config explicitAddressSpan 0
set_interface_property AVS_Config holdTime 0
set_interface_property AVS_Config linewrapBursts false
set_interface_property AVS_Config maximumPendingReadTransactions 1
set_interface_property AVS_Config maximumPendingWriteTransactions 0
set_interface_property AVS_Config readLatency 0
set_interface_property AVS_Config readWaitTime 1
set_interface_property AVS_Config setupTime 0
set_interface_property AVS_Config timingUnits Cycles
set_interface_property AVS_Config writeWaitTime 0
set_interface_property AVS_Config ENABLED true
set_interface_property AVS_Config EXPORT_OF ""
set_interface_property AVS_Config PORT_NAME_MAP ""
set_interface_property AVS_Config CMSIS_SVD_VARIABLES ""
set_interface_property AVS_Config SVD_ADDRESS_GROUP ""

add_interface_port AVS_Config AVS_waitrequest waitrequest Output 1
add_interface_port AVS_Config AVS_address address Input 3
add_interface_port AVS_Config AVS_byteenable byteenable Input 4
add_interface_port AVS_Config AVS_read read Input 1
add_interface_port AVS_Config AVS_readdata readdata Output 32
add_interface_port AVS_Config AVS_readdatavalid readdatavalid Output 1
add_interface_port AVS_Config AVS_write write Input 1
add_interface_port AVS_Config AVS_writedata writedata Input 32
set_interface_assignment AVS_Config embeddedsw.configuration.isFlash 0
set_interface_assignment AVS_Config embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment AVS_Config embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment AVS_Config embeddedsw.configuration.isPrintableDevice 0

