# TCL File Generated by Component Editor 18.1
# Tue Mar 17 12:26:39 MSK 2020
# DO NOT MODIFY


# 
# MILSTD_1553B "MILSTD_1553B" v16.1
#  2020.03.17.12:26:39
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module MILSTD_1553B
# 
set_module_property DESCRIPTION ""
set_module_property NAME MILSTD_1553B
set_module_property VERSION 16.1
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME MILSTD_1553B
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL MilStd1553_Transceiver
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file FIFO.vhd VHDL PATH ../src/MISC/FIFO.vhd
add_fileset_file timer.vhd VHDL PATH ../src/MISC/timer.vhd
add_fileset_file AVMM_Master_FIFO.vhd VHDL PATH ../src/MISC/AVMM_Master_FIFO.vhd
add_fileset_file ram_mux.vhd VHDL PATH ../src/MISC/ram_mux.vhd
add_fileset_file milstd_1553_pkg.vhd VHDL PATH ../src/MilStd1553_Transceiver/milstd_1553_pkg.vhd
add_fileset_file MILSTD1553RxPhy.vhd VHDL PATH ../src/MilStd1553_Transceiver/MILSTD1553RxPhy.vhd
add_fileset_file MILSTD1553TxPhy.vhd VHDL PATH ../src/MilStd1553_Transceiver/MILSTD1553TxPhy.vhd
add_fileset_file TxPhyDMUX.vhd VHDL PATH ../src/MilStd1553_Transceiver/TxPhyDMUX.vhd
add_fileset_file mil_RxPhyMUX.vhd VHDL PATH ../src/MilStd1553_Transceiver/mil_RxPhyMUX.vhd
add_fileset_file milstd1553_RxControl.vhd VHDL PATH ../src/MilStd1553_Transceiver/milstd1553_RxControl.vhd
add_fileset_file milstd1553_TxControl.vhd VHDL PATH ../src/MilStd1553_Transceiver/milstd1553_TxControl.vhd
add_fileset_file MilStd1553_Transceiver.vhd VHDL PATH ../src/MilStd1553_Transceiver/MilStd1553_Transceiver.vhd TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point Avalon_Clk
# 
add_interface Avalon_Clk clock end
set_interface_property Avalon_Clk clockRate 0
set_interface_property Avalon_Clk ENABLED true
set_interface_property Avalon_Clk EXPORT_OF ""
set_interface_property Avalon_Clk PORT_NAME_MAP ""
set_interface_property Avalon_Clk CMSIS_SVD_VARIABLES ""
set_interface_property Avalon_Clk SVD_ADDRESS_GROUP ""

add_interface_port Avalon_Clk Avalon_Clock clk Input 1


# 
# connection point Avalon_Reset
# 
add_interface Avalon_Reset reset end
set_interface_property Avalon_Reset associatedClock Avalon_Clk
set_interface_property Avalon_Reset synchronousEdges DEASSERT
set_interface_property Avalon_Reset ENABLED true
set_interface_property Avalon_Reset EXPORT_OF ""
set_interface_property Avalon_Reset PORT_NAME_MAP ""
set_interface_property Avalon_Reset CMSIS_SVD_VARIABLES ""
set_interface_property Avalon_Reset SVD_ADDRESS_GROUP ""

add_interface_port Avalon_Reset Avalon_nReset reset_n Input 1


# 
# connection point interrupt
# 
add_interface interrupt interrupt end
set_interface_property interrupt associatedAddressablePoint ""
set_interface_property interrupt associatedClock Avalon_Clk
set_interface_property interrupt associatedReset Avalon_Reset
set_interface_property interrupt bridgedReceiverOffset ""
set_interface_property interrupt bridgesToReceiver ""
set_interface_property interrupt ENABLED true
set_interface_property interrupt EXPORT_OF ""
set_interface_property interrupt PORT_NAME_MAP ""
set_interface_property interrupt CMSIS_SVD_VARIABLES ""
set_interface_property interrupt SVD_ADDRESS_GROUP ""

add_interface_port interrupt Interrupt irq Output 1


# 
# connection point AVS_Config
# 
add_interface AVS_Config avalon end
set_interface_property AVS_Config addressUnits WORDS
set_interface_property AVS_Config associatedClock Avalon_Clk
set_interface_property AVS_Config associatedReset Avalon_Reset
set_interface_property AVS_Config bitsPerSymbol 8
set_interface_property AVS_Config burstOnBurstBoundariesOnly false
set_interface_property AVS_Config burstcountUnits WORDS
set_interface_property AVS_Config explicitAddressSpan 0
set_interface_property AVS_Config holdTime 0
set_interface_property AVS_Config linewrapBursts false
set_interface_property AVS_Config maximumPendingReadTransactions 1
set_interface_property AVS_Config maximumPendingWriteTransactions 0
set_interface_property AVS_Config readLatency 0
set_interface_property AVS_Config readWaitTime 1
set_interface_property AVS_Config setupTime 0
set_interface_property AVS_Config timingUnits Cycles
set_interface_property AVS_Config writeWaitTime 0
set_interface_property AVS_Config ENABLED true
set_interface_property AVS_Config EXPORT_OF ""
set_interface_property AVS_Config PORT_NAME_MAP ""
set_interface_property AVS_Config CMSIS_SVD_VARIABLES ""
set_interface_property AVS_Config SVD_ADDRESS_GROUP ""

add_interface_port AVS_Config AVS_waitrequest waitrequest Output 1
add_interface_port AVS_Config AVS_address address Input 2
add_interface_port AVS_Config AVS_byteenable byteenable Input 4
add_interface_port AVS_Config AVS_read read Input 1
add_interface_port AVS_Config AVS_readdata readdata Output 32
add_interface_port AVS_Config AVS_readdatavalid readdatavalid Output 1
add_interface_port AVS_Config AVS_write write Input 1
add_interface_port AVS_Config AVS_writedata writedata Input 32
set_interface_assignment AVS_Config embeddedsw.configuration.isFlash 0
set_interface_assignment AVS_Config embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment AVS_Config embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment AVS_Config embeddedsw.configuration.isPrintableDevice 0


# 
# connection point AV2RAM
# 
add_interface AV2RAM avalon start
set_interface_property AV2RAM addressUnits WORDS
set_interface_property AV2RAM associatedClock Avalon_Clk
set_interface_property AV2RAM associatedReset Avalon_Reset
set_interface_property AV2RAM bitsPerSymbol 8
set_interface_property AV2RAM burstOnBurstBoundariesOnly false
set_interface_property AV2RAM burstcountUnits WORDS
set_interface_property AV2RAM doStreamReads false
set_interface_property AV2RAM doStreamWrites false
set_interface_property AV2RAM holdTime 0
set_interface_property AV2RAM linewrapBursts false
set_interface_property AV2RAM maximumPendingReadTransactions 1
set_interface_property AV2RAM maximumPendingWriteTransactions 0
set_interface_property AV2RAM readLatency 0
set_interface_property AV2RAM readWaitTime 1
set_interface_property AV2RAM setupTime 0
set_interface_property AV2RAM timingUnits Cycles
set_interface_property AV2RAM writeWaitTime 0
set_interface_property AV2RAM ENABLED true
set_interface_property AV2RAM EXPORT_OF ""
set_interface_property AV2RAM PORT_NAME_MAP ""
set_interface_property AV2RAM CMSIS_SVD_VARIABLES ""
set_interface_property AV2RAM SVD_ADDRESS_GROUP ""

add_interface_port AV2RAM AV2RAM_address address Output 12
add_interface_port AV2RAM AV2RAM_byteenable byteenable Output 4
add_interface_port AV2RAM AV2RAM_read read Output 1
add_interface_port AV2RAM AV2RAM_readdata readdata Input 32
add_interface_port AV2RAM AV2RAM_readdatavalid readdatavalid Input 1
add_interface_port AV2RAM AV2RAM_waitrequest waitrequest Input 1
add_interface_port AV2RAM AV2RAM_write write Output 1
add_interface_port AV2RAM AV2RAM_writedata writedata Output 32


# 
# connection point AV2RAM2
# 
add_interface AV2RAM2 avalon start
set_interface_property AV2RAM2 addressUnits WORDS
set_interface_property AV2RAM2 associatedClock Avalon_Clk
set_interface_property AV2RAM2 associatedReset Avalon_Reset
set_interface_property AV2RAM2 bitsPerSymbol 8
set_interface_property AV2RAM2 burstOnBurstBoundariesOnly false
set_interface_property AV2RAM2 burstcountUnits WORDS
set_interface_property AV2RAM2 doStreamReads false
set_interface_property AV2RAM2 doStreamWrites false
set_interface_property AV2RAM2 holdTime 0
set_interface_property AV2RAM2 linewrapBursts false
set_interface_property AV2RAM2 maximumPendingReadTransactions 1
set_interface_property AV2RAM2 maximumPendingWriteTransactions 0
set_interface_property AV2RAM2 readLatency 0
set_interface_property AV2RAM2 readWaitTime 1
set_interface_property AV2RAM2 setupTime 0
set_interface_property AV2RAM2 timingUnits Cycles
set_interface_property AV2RAM2 writeWaitTime 0
set_interface_property AV2RAM2 ENABLED true
set_interface_property AV2RAM2 EXPORT_OF ""
set_interface_property AV2RAM2 PORT_NAME_MAP ""
set_interface_property AV2RAM2 CMSIS_SVD_VARIABLES ""
set_interface_property AV2RAM2 SVD_ADDRESS_GROUP ""

add_interface_port AV2RAM2 AV2RAM2_address address Output 12
add_interface_port AV2RAM2 AV2RAM2_byteenable byteenable Output 4
add_interface_port AV2RAM2 AV2RAM2_read read Output 1
add_interface_port AV2RAM2 AV2RAM2_readdata readdata Input 32
add_interface_port AV2RAM2 AV2RAM2_readdatavalid readdatavalid Input 1
add_interface_port AV2RAM2 AV2RAM2_waitrequest waitrequest Input 1
add_interface_port AV2RAM2 AV2RAM2_write write Output 1
add_interface_port AV2RAM2 AV2RAM2_writedata writedata Output 32


# 
# connection point AV2PCIE
# 
add_interface AV2PCIE avalon end
set_interface_property AV2PCIE addressUnits WORDS
set_interface_property AV2PCIE associatedClock Avalon_Clk
set_interface_property AV2PCIE associatedReset Avalon_Reset
set_interface_property AV2PCIE bitsPerSymbol 8
set_interface_property AV2PCIE burstOnBurstBoundariesOnly false
set_interface_property AV2PCIE burstcountUnits WORDS
set_interface_property AV2PCIE explicitAddressSpan 0
set_interface_property AV2PCIE holdTime 0
set_interface_property AV2PCIE linewrapBursts false
set_interface_property AV2PCIE maximumPendingReadTransactions 1
set_interface_property AV2PCIE maximumPendingWriteTransactions 0
set_interface_property AV2PCIE readLatency 0
set_interface_property AV2PCIE readWaitTime 1
set_interface_property AV2PCIE setupTime 0
set_interface_property AV2PCIE timingUnits Cycles
set_interface_property AV2PCIE writeWaitTime 0
set_interface_property AV2PCIE ENABLED true
set_interface_property AV2PCIE EXPORT_OF ""
set_interface_property AV2PCIE PORT_NAME_MAP ""
set_interface_property AV2PCIE CMSIS_SVD_VARIABLES ""
set_interface_property AV2PCIE SVD_ADDRESS_GROUP ""

add_interface_port AV2PCIE AV2PCIE_waitrequest waitrequest Output 1
add_interface_port AV2PCIE AV2PCIE_address address Input 12
add_interface_port AV2PCIE AV2PCIE_byteenable byteenable Input 4
add_interface_port AV2PCIE AV2PCIE_read read Input 1
add_interface_port AV2PCIE AV2PCIE_readdata readdata Output 32
add_interface_port AV2PCIE AV2PCIE_readdatavalid readdatavalid Output 1
add_interface_port AV2PCIE AV2PCIE_write write Input 1
add_interface_port AV2PCIE AV2PCIE_writedata writedata Input 32
set_interface_assignment AV2PCIE embeddedsw.configuration.isFlash 0
set_interface_assignment AV2PCIE embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment AV2PCIE embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment AV2PCIE embeddedsw.configuration.isPrintableDevice 0


# 
# connection point mil_std_1553b
# 
add_interface mil_std_1553b conduit end
set_interface_property mil_std_1553b associatedClock mil_std_1553b_clock
set_interface_property mil_std_1553b associatedReset ""
set_interface_property mil_std_1553b ENABLED true
set_interface_property mil_std_1553b EXPORT_OF ""
set_interface_property mil_std_1553b PORT_NAME_MAP ""
set_interface_property mil_std_1553b CMSIS_SVD_VARIABLES ""
set_interface_property mil_std_1553b SVD_ADDRESS_GROUP ""

add_interface_port mil_std_1553b MilStd1553_LineIA1 line1_rx_p Input 1
add_interface_port mil_std_1553b MilStd1553_LineIB1 line1_rx_n Input 1
add_interface_port mil_std_1553b MilStd1553_RxEn1 line1_rxen Output 1
add_interface_port mil_std_1553b MilStd1553_LineIA2 line2_rx_p Input 1
add_interface_port mil_std_1553b MilStd1553_LineIB2 line2_rx_n Input 1
add_interface_port mil_std_1553b MilStd1553_RxEn2 line2_rxen Output 1
add_interface_port mil_std_1553b MilStd1553_LineOA1 line1_tx_p Output 1
add_interface_port mil_std_1553b MilStd1553_LineOB1 line1_tx_n Output 1
add_interface_port mil_std_1553b MilStd1553_TxEn1 line1_txen Output 1
add_interface_port mil_std_1553b MilStd1553_LineOA2 line2_tx_p Output 1
add_interface_port mil_std_1553b MilStd1553_LineOB2 line2_tx_n Output 1
add_interface_port mil_std_1553b MilStd1553_TxEn2 line2_txen Output 1
add_interface_port mil_std_1553b NodeAddrHard nodeaddr Input 5
add_interface_port mil_std_1553b LineTurnOFF1 line1_off Output 1
add_interface_port mil_std_1553b LineTurnOFF2 line2_off Output 1


# 
# connection point mil_std_1553b_clock
# 
add_interface mil_std_1553b_clock clock end
set_interface_property mil_std_1553b_clock clockRate 0
set_interface_property mil_std_1553b_clock ENABLED true
set_interface_property mil_std_1553b_clock EXPORT_OF ""
set_interface_property mil_std_1553b_clock PORT_NAME_MAP ""
set_interface_property mil_std_1553b_clock CMSIS_SVD_VARIABLES ""
set_interface_property mil_std_1553b_clock SVD_ADDRESS_GROUP ""

add_interface_port mil_std_1553b_clock MilStd1553_Clock clk Input 1

