# TCL File Generated by Component Editor 18.1
# Thu Oct 28 13:01:37 MSK 2021
# DO NOT MODIFY


# 
# videocore_cnfg "videocore_cnfg" v1.0
#  2021.10.28.13:01:37
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module videocore_cnfg
# 
set_module_property DESCRIPTION ""
set_module_property NAME videocore_cnfg
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME videocore_cnfg
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL videocore_cnfg
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file videocore_cnfg.sv SYSTEM_VERILOG PATH configurator/videocore_cnfg.sv TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter VIDECORE_ADDR INTEGER 0
set_parameter_property VIDECORE_ADDR DEFAULT_VALUE 0
set_parameter_property VIDECORE_ADDR DISPLAY_NAME VIDECORE_ADDR
set_parameter_property VIDECORE_ADDR TYPE INTEGER
set_parameter_property VIDECORE_ADDR UNITS None
set_parameter_property VIDECORE_ADDR ALLOWED_RANGES -2147483648:2147483647
set_parameter_property VIDECORE_ADDR HDL_PARAMETER true


# 
# display items
# 


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1


# 
# connection point avalon_master
# 
add_interface avalon_master avalon start
set_interface_property avalon_master addressUnits SYMBOLS
set_interface_property avalon_master associatedClock clock
set_interface_property avalon_master associatedReset reset
set_interface_property avalon_master bitsPerSymbol 8
set_interface_property avalon_master burstOnBurstBoundariesOnly false
set_interface_property avalon_master burstcountUnits WORDS
set_interface_property avalon_master doStreamReads false
set_interface_property avalon_master doStreamWrites false
set_interface_property avalon_master holdTime 0
set_interface_property avalon_master linewrapBursts false
set_interface_property avalon_master maximumPendingReadTransactions 0
set_interface_property avalon_master maximumPendingWriteTransactions 0
set_interface_property avalon_master readLatency 0
set_interface_property avalon_master readWaitTime 1
set_interface_property avalon_master setupTime 0
set_interface_property avalon_master timingUnits Cycles
set_interface_property avalon_master writeWaitTime 0
set_interface_property avalon_master ENABLED true
set_interface_property avalon_master EXPORT_OF ""
set_interface_property avalon_master PORT_NAME_MAP ""
set_interface_property avalon_master CMSIS_SVD_VARIABLES ""
set_interface_property avalon_master SVD_ADDRESS_GROUP ""

add_interface_port avalon_master amm_waitrequest waitrequest Input 1
add_interface_port avalon_master amm_write write Output 1
add_interface_port avalon_master amm_read read Output 1
add_interface_port avalon_master amm_address address Output 32
add_interface_port avalon_master amm_writedata writedata Output 32
add_interface_port avalon_master amm_readdatavalid readdatavalid Input 1
add_interface_port avalon_master amm_readdata readdata Input 32


# 
# connection point gp
# 
add_interface gp conduit end
set_interface_property gp associatedClock ""
set_interface_property gp associatedReset ""
set_interface_property gp ENABLED true
set_interface_property gp EXPORT_OF ""
set_interface_property gp PORT_NAME_MAP ""
set_interface_property gp CMSIS_SVD_VARIABLES ""
set_interface_property gp SVD_ADDRESS_GROUP ""

add_interface_port gp gp_inputs gp_inputs Input 8
add_interface_port gp gp_outputs gp_outputs Output 8


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clock clk Input 1

