# TCL File Generated by Component Editor 18.1
# Mon Jul 05 16:24:16 MSK 2021
# DO NOT MODIFY


# 
# arinc429 "arinc429" v1.0
#  2021.07.05.16:24:16
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module arinc429
# 
set_module_property DESCRIPTION ""
set_module_property NAME arinc429
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME arinc429
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false
set_module_property VALIDATION_CALLBACK validate


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL arinc429
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file arinc429.sv SYSTEM_VERILOG PATH ./arinc429.sv TOP_LEVEL_FILE
add_fileset_file arinc_tx_controller.sv SYSTEM_VERILOG PATH ./arinc_tx_controller.sv
add_fileset_file arinc_rx_controller.sv SYSTEM_VERILOG PATH ./arinc_rx_controller.sv
add_fileset_file arinc429_tx.sv SYSTEM_VERILOG PATH ./arinc429_tx.sv
add_fileset_file arinc429_rx.sv SYSTEM_VERILOG PATH ./arinc429_rx.sv
add_fileset_file SYNC_PE.sv SYSTEM_VERILOG PATH ./SYNC_PE.sv
add_fileset_file DDIN.sv SYSTEM_VERILOG PATH ./DDIN.sv
add_fileset_file PEIN.sv SYSTEM_VERILOG PATH ./PEIN.sv
add_fileset_file filter_input.sv SYSTEM_VERILOG PATH ./filter_input.sv


# 
# parameters
# 
add_parameter REC_NUMB INTEGER 16 ""
set_parameter_property REC_NUMB DEFAULT_VALUE 16
set_parameter_property REC_NUMB DISPLAY_NAME "RX channels number"
set_parameter_property REC_NUMB TYPE INTEGER
set_parameter_property REC_NUMB UNITS None
set_parameter_property REC_NUMB ALLOWED_RANGES -2147483648:2147483647
set_parameter_property REC_NUMB DESCRIPTION ""
set_parameter_property REC_NUMB HDL_PARAMETER true
add_parameter TR_NUMB INTEGER 6
set_parameter_property TR_NUMB DEFAULT_VALUE 6
set_parameter_property TR_NUMB DISPLAY_NAME "TX channels number"
set_parameter_property TR_NUMB TYPE INTEGER
set_parameter_property TR_NUMB UNITS None
set_parameter_property TR_NUMB ALLOWED_RANGES -2147483648:2147483647
set_parameter_property TR_NUMB HDL_PARAMETER true
add_parameter INPUTFREQUENCY INTEGER 0 CLOCK_RATE
set_parameter_property INPUTFREQUENCY DEFAULT_VALUE 0
set_parameter_property INPUTFREQUENCY ALLOWED_RANGES 0:250000000
set_parameter_property INPUTFREQUENCY DISPLAY_NAME "Input frequency"
set_parameter_property INPUTFREQUENCY TYPE INTEGER
set_parameter_property INPUTFREQUENCY UNITS Hertz
set_parameter_property INPUTFREQUENCY HDL_PARAMETER true
set_parameter_property INPUTFREQUENCY SYSTEM_INFO_TYPE CLOCK_RATE
set_parameter_property INPUTFREQUENCY SYSTEM_INFO_ARG clock


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1


# 
# connection point ams
# 
add_interface ams avalon end
set_interface_property ams addressUnits SYMBOLS
set_interface_property ams associatedClock clock
set_interface_property ams associatedReset reset
set_interface_property ams bitsPerSymbol 8
set_interface_property ams burstOnBurstBoundariesOnly false
set_interface_property ams burstcountUnits SYMBOLS
set_interface_property ams explicitAddressSpan 0
set_interface_property ams holdTime 0
set_interface_property ams linewrapBursts false
set_interface_property ams maximumPendingReadTransactions 1
set_interface_property ams maximumPendingWriteTransactions 0
set_interface_property ams readLatency 0
set_interface_property ams readWaitTime 1
set_interface_property ams setupTime 0
set_interface_property ams timingUnits Cycles
set_interface_property ams writeWaitTime 0
set_interface_property ams ENABLED true
set_interface_property ams EXPORT_OF ""
set_interface_property ams PORT_NAME_MAP ""
set_interface_property ams CMSIS_SVD_VARIABLES ""
set_interface_property ams SVD_ADDRESS_GROUP ""

add_interface_port ams ams_waitrequest waitrequest Output 1
add_interface_port ams ams_write write Input 1
add_interface_port ams ams_read read Input 1
add_interface_port ams ams_address address Input 21
add_interface_port ams ams_writedata writedata Input 32
add_interface_port ams ams_readdatavalid readdatavalid Output 1
add_interface_port ams ams_readdata readdata Output 32
set_interface_assignment ams embeddedsw.configuration.isFlash 0
set_interface_assignment ams embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment ams embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment ams embeddedsw.configuration.isPrintableDevice 0


# 
# connection point conduit_end
# 
add_interface conduit_end conduit end
set_interface_property conduit_end associatedClock clock
set_interface_property conduit_end associatedReset ""
set_interface_property conduit_end ENABLED true
set_interface_property conduit_end EXPORT_OF ""
set_interface_property conduit_end PORT_NAME_MAP ""
set_interface_property conduit_end CMSIS_SVD_VARIABLES ""
set_interface_property conduit_end SVD_ADDRESS_GROUP ""

add_interface_port conduit_end InputA inputa Input REC_NUMB
add_interface_port conduit_end InputB inputb Input REC_NUMB
add_interface_port conduit_end OutputA outputa Output TR_NUMB
add_interface_port conduit_end OutputB outputb Output TR_NUMB
add_interface_port conduit_end SlewRate slewrate Output TR_NUMB
add_interface_port conduit_end TestAB testab Output 2


# 
# connection point interrupt_sender
# 
add_interface interrupt_sender interrupt end
set_interface_property interrupt_sender associatedAddressablePoint ""
set_interface_property interrupt_sender associatedClock clock
set_interface_property interrupt_sender associatedReset reset
set_interface_property interrupt_sender bridgedReceiverOffset ""
set_interface_property interrupt_sender bridgesToReceiver ""
set_interface_property interrupt_sender ENABLED true
set_interface_property interrupt_sender EXPORT_OF ""
set_interface_property interrupt_sender PORT_NAME_MAP ""
set_interface_property interrupt_sender CMSIS_SVD_VARIABLES ""
set_interface_property interrupt_sender SVD_ADDRESS_GROUP ""

add_interface_port interrupt_sender IRQ irq Output REC_NUMB+TR_NUMB


proc validate {} {

	set_module_assignment embeddedsw.CMacro.RX_CHANNELS   [ get_parameter_value REC_NUMB ]
	set_module_assignment embeddedsw.CMacro.RX_CSR_OFFSET "0x00004000"
	set_module_assignment embeddedsw.CMacro.RX_MEM_OFFSET "0x00000000"
	set_module_assignment embeddedsw.CMacro.RX_CSR_ALIGN  "0x00010000"
	set_module_assignment embeddedsw.CMacro.RX_MEM_ALIGN  "0x00010000"

	set_module_assignment embeddedsw.CMacro.TX_CHANNELS   [ get_parameter_value TR_NUMB ]
	set_module_assignment embeddedsw.CMacro.TX_CSR_OFFSET "0x00104000"
	set_module_assignment embeddedsw.CMacro.TX_MEM_OFFSET "0x00100000"
	set_module_assignment embeddedsw.CMacro.TX_CSR_ALIGN  "0x00010000"
	set_module_assignment embeddedsw.CMacro.TX_MEM_ALIGN  "0x00010000"

}
