# TCL File Generated by Component Editor 18.1
# Fri Dec 03 16:46:55 MSK 2021
# DO NOT MODIFY


# 
# dev_info "dev_info" v1.0
#  2021.12.03.16:46:55
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module dev_info
# 
set_module_property DESCRIPTION ""
set_module_property NAME dev_info
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME dev_info
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL dev_info
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file dev_info.sv SYSTEM_VERILOG PATH ./dev_info.sv TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter INPUT_CLOCK INTEGER 100000000
set_parameter_property INPUT_CLOCK DEFAULT_VALUE 100000000
set_parameter_property INPUT_CLOCK DISPLAY_NAME INPUT_CLOCK
set_parameter_property INPUT_CLOCK TYPE INTEGER
set_parameter_property INPUT_CLOCK UNITS Hertz
set_parameter_property INPUT_CLOCK HDL_PARAMETER true
set_parameter_property INPUT_CLOCK SYSTEM_INFO_TYPE CLOCK_RATE
set_parameter_property INPUT_CLOCK SYSTEM_INFO_ARG clock

# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point ams
# 
add_interface ams avalon end
set_interface_property ams addressUnits WORDS
set_interface_property ams associatedClock clock
set_interface_property ams associatedReset reset
set_interface_property ams bitsPerSymbol 8
set_interface_property ams burstOnBurstBoundariesOnly false
set_interface_property ams burstcountUnits WORDS
set_interface_property ams explicitAddressSpan 0
set_interface_property ams holdTime 0
set_interface_property ams linewrapBursts false
set_interface_property ams maximumPendingReadTransactions 0
set_interface_property ams maximumPendingWriteTransactions 0
set_interface_property ams readLatency 0
set_interface_property ams readWaitTime 1
set_interface_property ams setupTime 0
set_interface_property ams timingUnits Cycles
set_interface_property ams writeWaitTime 0
set_interface_property ams ENABLED true
set_interface_property ams EXPORT_OF ""
set_interface_property ams PORT_NAME_MAP ""
set_interface_property ams CMSIS_SVD_VARIABLES ""
set_interface_property ams SVD_ADDRESS_GROUP ""

add_interface_port ams ams_read read Input 1
add_interface_port ams ams_address address Input 3
add_interface_port ams ams_readdata readdata Output 32
set_interface_assignment ams embeddedsw.configuration.isFlash 0
set_interface_assignment ams embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment ams embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment ams embeddedsw.configuration.isPrintableDevice 0


# 
# connection point conduit_end
# 
add_interface conduit_end conduit end
set_interface_property conduit_end associatedClock clock
set_interface_property conduit_end associatedReset ""
set_interface_property conduit_end ENABLED true
set_interface_property conduit_end EXPORT_OF ""
set_interface_property conduit_end PORT_NAME_MAP ""
set_interface_property conduit_end CMSIS_SVD_VARIABLES ""
set_interface_property conduit_end SVD_ADDRESS_GROUP ""

add_interface_port conduit_end crc_in crc_in Input 32
add_interface_port conduit_end mkio_address mkio_address Input 5

