# TCL File Generated by Component Editor 18.1
# Tue Oct 05 16:32:54 MSK 2021
# DO NOT MODIFY


# 
# discr_cmd_out "discr_cmd_out" v18.1
#  2021.10.05.16:32:54
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module discr_cmd_out
# 
set_module_property DESCRIPTION ""
set_module_property NAME discr_cmd_out
set_module_property VERSION 18.1
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME discr_cmd_out
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL discr_cmd_out
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file discr_cmd_out.sv SYSTEM_VERILOG PATH discr_cmd_out.sv TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter CLOCK_FREQ INTEGER 0 CLOCK_RATE
set_parameter_property CLOCK_FREQ DEFAULT_VALUE 0
set_parameter_property CLOCK_FREQ DISPLAY_NAME CLOCK_FREQ
set_parameter_property CLOCK_FREQ TYPE INTEGER
set_parameter_property CLOCK_FREQ UNITS Hertz
set_parameter_property CLOCK_FREQ ALLOWED_RANGES 0:250000000
set_parameter_property CLOCK_FREQ DESCRIPTION CLOCK_RATE
set_parameter_property CLOCK_FREQ HDL_PARAMETER true
set_parameter_property CLOCK_FREQ SYSTEM_INFO_TYPE CLOCK_RATE
set_parameter_property CLOCK_FREQ SYSTEM_INFO_ARG clock
add_parameter TIMEOUT_MS INTEGER 0
set_parameter_property TIMEOUT_MS DEFAULT_VALUE 0
set_parameter_property TIMEOUT_MS DISPLAY_NAME TIMEOUT_MS
set_parameter_property TIMEOUT_MS TYPE INTEGER
set_parameter_property TIMEOUT_MS UNITS None
set_parameter_property TIMEOUT_MS ALLOWED_RANGES 0:2147483647
set_parameter_property TIMEOUT_MS HDL_PARAMETER true
add_parameter COUNT INTEGER 32
set_parameter_property COUNT DEFAULT_VALUE 32
set_parameter_property COUNT DISPLAY_NAME COUNT
set_parameter_property COUNT TYPE INTEGER
set_parameter_property COUNT UNITS None
set_parameter_property COUNT ALLOWED_RANGES 1:32
set_parameter_property COUNT HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1


# 
# connection point csr
# 
add_interface csr avalon end
set_interface_property csr addressUnits WORDS
set_interface_property csr associatedClock clock
set_interface_property csr associatedReset reset
set_interface_property csr bitsPerSymbol 8
set_interface_property csr burstOnBurstBoundariesOnly false
set_interface_property csr burstcountUnits WORDS
set_interface_property csr explicitAddressSpan 0
set_interface_property csr holdTime 0
set_interface_property csr linewrapBursts false
set_interface_property csr maximumPendingReadTransactions 1
set_interface_property csr maximumPendingWriteTransactions 0
set_interface_property csr readLatency 0
set_interface_property csr readWaitTime 1
set_interface_property csr setupTime 0
set_interface_property csr timingUnits Cycles
set_interface_property csr writeWaitTime 0
set_interface_property csr ENABLED true
set_interface_property csr EXPORT_OF ""
set_interface_property csr PORT_NAME_MAP ""
set_interface_property csr CMSIS_SVD_VARIABLES ""
set_interface_property csr SVD_ADDRESS_GROUP ""

add_interface_port csr ams_waitrequest waitrequest Output 1
add_interface_port csr ams_write write Input 1
add_interface_port csr ams_read read Input 1
add_interface_port csr ams_address address Input 2
add_interface_port csr ams_writedata writedata Input 32
add_interface_port csr ams_readdatavalid readdatavalid Output 1
add_interface_port csr ams_readdata readdata Output 32
set_interface_assignment csr embeddedsw.configuration.isFlash 0
set_interface_assignment csr embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment csr embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment csr embeddedsw.configuration.isPrintableDevice 0


# 
# connection point discr_cmd
# 
add_interface discr_cmd conduit end
set_interface_property discr_cmd associatedClock ""
set_interface_property discr_cmd associatedReset ""
set_interface_property discr_cmd ENABLED true
set_interface_property discr_cmd EXPORT_OF ""
set_interface_property discr_cmd PORT_NAME_MAP ""
set_interface_property discr_cmd CMSIS_SVD_VARIABLES ""
set_interface_property discr_cmd SVD_ADDRESS_GROUP ""

add_interface_port discr_cmd fault fault Input COUNT
add_interface_port discr_cmd out export Output COUNT


# 
# connection point irq
# 
add_interface irq interrupt end
set_interface_property irq associatedAddressablePoint csr
set_interface_property irq associatedClock clock
set_interface_property irq associatedReset reset
set_interface_property irq bridgedReceiverOffset 0
set_interface_property irq bridgesToReceiver ""
set_interface_property irq ENABLED true
set_interface_property irq EXPORT_OF ""
set_interface_property irq PORT_NAME_MAP ""
set_interface_property irq CMSIS_SVD_VARIABLES ""
set_interface_property irq SVD_ADDRESS_GROUP ""

add_interface_port irq irq irq Output 1

